### ISSUE TITLE
Missing parameters from getToken method

### ISSUE THREAD

**Issue by dross91786** [lelylan/simple-oauth2#100]
The only two args that getToken seems to be looking for are params & callback.  The only param being passed was 'grant_type'.  This was not functioning properly and upon request for a token with code, I was getting an 'invalid_client' error. Was able to fix this by adding 'client_id & 'clientSecret' to the params.
```
function getToken(params, callback) {
    params.grant_type = 'authorization_code';
    params.client_id = config.clientID;
    params.clientSecret = config.clientSecret;

    return core
      .api('POST', config.tokenPath, params)
      .nodeify(callback);
  }
```

**Comment by jonathansamines** [comment]
This should be working properly. Please try using the v1.0.0. 

Feel free to re-open if the issue persist.
