### ISSUE TITLE
accessToken.reoke request is unauthorised

### ISSUE THREAD

**Issue by astondg** [lelylan/simple-oauth2#106]
As far as I can tell, the accessToken.revoke function does not pass the current access token to the core.post function and so this request is sent without the 'Authorization: bearer xxxx' header.

RFC 7009 _'OAuth 2.0 Token Revocation'_, section 2.1 _'Revocation Request'_ (https://tools.ietf.org/html/rfc7009#page-4) states

> The client also includes its authentication credentials as described in Section 2.3. of [RFC6749]

**Comment by jonathansamines** [comment]
Hi @astondg what version of simple-oauth are you using?

**Comment by astondg** [comment]
Hi @jonathansamines I am using 1.0.0 (I had the issue with 0.5.1 but I upgraded hoping it would resolve, it did not).

The endpoint I'm hitting (via `accessToken.revoke`) to revoke the token is returning a `401 Unauthorized` status and I can't see the Authorization header being passed to it.

**Comment by jonathansamines** [comment]
Hi @astondg I made a couple of tests, and seems like the `Authorization` header is sent according to the specs (using the Basic protocol with client_id and secret being encoded on it). Also the current access token is also sent as part of the POST body (www-form-urlencoded).

You could put simple-oauth2 in debug mode (`DEBUG=*simple-oauth2* npm start`) to see what is going on with the underlying request. 

Hope that helps.

**Comment by astondg** [comment]
Ah, so I think the issue is that the authorization server that I'm contacting requires the `Authorization` Bearer protocol rather than Basic, with the current accessToken in that header. It isn't checking the POST body.

My understanding of the spec was that the authorization server is able to determine the authentication method?
> If the client type is confidential, the client and authorization server establish a client authentication method suitable for the security requirements of the authorization server

I'll test again in debug mode to verify exactly what is happen and post the results back here.

**Comment by astondg** [comment]
I have followed this issue up with the developer of the authorization server API and determined that it does not meet the OAuth 2.0 specification. That is where the problem lies. My apologies. I will close this issue.
