### ISSUE TITLE
TypeScript Version

### ISSUE THREAD

**Issue by ChristopheCubat** [lelylan/simple-oauth2#109]
Hi,

I was wondering if it's possible to make simple-oauth2 compatible to typescript?

https://www.typescriptlang.org/docs/handbook/modules.html 

Thanks in advance

**Comment by jonathansamines** [comment]
Hey @ChristopheCubat do you know what is required for a library to support Typescript? I am not familiar with that environment.

**Comment by ChristopheCubat** [comment]
Hey @jonathansamines,

To my understanding with the link from the first message and https://basarat.gitbooks.io/typescript/content/docs/quick/nodejs.html, you should have only to type the api of your modules within a single file :

```
You can even use other node modules written in TypeScript. As a module author, one real thing you should do:
you might want to have a typings field (e.g. src/index) in your package.json similar to the main field to point to the default TypeScript definition export. For an example look at package.json for csx.
Example package: npm install csx for csx, usage: import csx = require('csx').
```

**Comment by jonathansamines** [comment]
Hi @ChristopheCubat even when I am not against adding support for TS, I dont have the time to get deeper into what is required to. A PR would be welcome though :)

**Comment by CharnjeetIotasol** [comment]
Any update on this ? I need the typescript version of this.

**Comment by jonathansamines** [comment]
@CharnjeetIotasol as in my original response, I am open to PR's to add typescript support.
