### ISSUE TITLE
client object required despite documented as optional

### ISSUE THREAD

**Issue by twelve17** [lelylan/simple-oauth2#111]
When attempting to create() an oauth2 instance without a client object, the following error occurs:

``` 
  ValidationError: Invalid options provided to simple-oauth2. {
      "client": {
      "id" [1]: -- missing --
    },
    "auth": { 
       <removed>
     }
  }

[1] "id" is required

```

The [current README.md](https://github.com/lelylan/simple-oauth2/blob/a66cff4bb4dd6d4383254880f9077396ffd3c50f/README.md) states that the `client` attribute is an optional object, yet it seems to be required per [these validations](https://github.com/lelylan/simple-oauth2/blob/master/index.js#L13).

**Comment by twelve17** [comment]
My initial report is slightly wrong. I was indeed passing in a client object (although empty).  However, it does still seem to fail when omitting the client object altogether:
```
ValidationError: Invalid options provided to simple-oauth2. {
  "auth": <removed> 
  "client" [1]: -- missing --
}

[1] "client" is required
```

**Comment by jonathansamines** [comment]
Hi @twelve17 yes, that is a problem with the documentation, the client property can never be optional, bacause it contains the application´s id and secret information. Sorry about that.

I´ll try to fix the documentation later.

**Comment by aktiviseerimiskeskus** [comment]
I have a similar problem.
`ValidationError: Invalid options provided to simple-oauth2 {`
`  "clientID": "*MY_ID*",`
`  "clientSecret": "*MY_Secret*",`
`  "site": "URL",`
`  "tokenPath": "/oauth/access_token",`
`  "authorizationPath": "/oauth/authorize",`
`  "client" [1]: -- missing --`
`}`

`[1] "client" is required`

I do not need client, i have a clientID.
