### ISSUE TITLE
Read state in callback

### ISSUE THREAD

**Issue by caub** [lelylan/simple-oauth2#113]
I'd like to know if I could set a dynamic state https://github.com/lelylan/simple-oauth2/blob/master/example/index.js#L23 (this building authorizationUri in /auth endpoint), then read this state later in /callback endpoint?

**Comment by jonathansamines** [comment]
Hi @caub , the purpose of that field is defined in the OAuth2 standard (See https://tools.ietf.org/html/rfc6749#section-4.1.1), and thus is never exposed. What do you want to do?

**Comment by caub** [comment]
I want to set a state at the beginning of OAuth2 process (client asking provider url), then recover this state in the callback

**Comment by jonathansamines** [comment]
@caub the only way to do so, is by using [sessions](https://github.com/expressjs/session), `cookies` or other persistence mechanism, because both calls are done in two different request.

**Comment by jonathansamines** [comment]
If you still have questions, feel free to reopen.
