### ISSUE TITLE
Refresh token [TypeError]

### ISSUE THREAD

**Issue by Matlino** [lelylan/simple-oauth2#114]
"Refresh token [TypeError: Cannot use 'in' operator to search for 'expires_at' in" <access token, refresh token and other parameter from get request>

Seems like your library is not parsing url parameters to JSON. I get the same error while using this function
`oauth2.accessToken.create(token);`
but here i could parse the token from url paramter to JSON  like this
`oauth2.accessToken.create(querystring.parse(token));`
and it was fixed.

Problem is when i am refreshing expired token with
`token.refresh(function(error, result) {});`
I assume the token expiration is going to be evaluate right after token was acquired so i dont have a chance to convert it to JSON.

Am i doing it wrong? Or is this a issue?

**Comment by jonathansamines** [comment]
@Matlino the reason is because you are passing something to those functions, that is not an object. The library expects to work with JSON payloads and not with "strings".

**Comment by Matlino** [comment]
Yes, exactly,  this is the problem. But how can i affect the flow of
refresh function?
I am just passing callback function as an argument. Function itself is
doing the request for new token and also parsing the response string. Error
happen when i call this function. Am i missing something?

Dňa 23. 11. 2016 3:36 používateľ "Jonathan Samines" <
notifications@github.com> napísal:

**Comment by jonathansamines** [comment]
Perhaps your endpoint do not support JSON as a content type, as you can see [here](https://github.com/lelylan/simple-oauth2/blob/master/index.js#L27) the library request to the auth-server a JSON response, if you are not receiving that, is likely because your server not supporting JSON as a content type.

Currently there is no way to affect or intercept those functions behaviour.

**Comment by Matlino** [comment]
I see, thats the problem. I checked content type of refresh token response and  you were right:
content-type →text/plain;charset=ISO-8859-1

So i guess i am gonna code the refresh token flow myself.

Thank you for clarifying this for me. :)
