### ISSUE TITLE
expires_at is broken

### ISSUE THREAD

**Issue by arekkas** [lelylan/simple-oauth2#115]
Not sure what's happening, but it looks like `https://github.com/lelylan/simple-oauth2/blob/master/lib/client/access-token.js#L25` is broken, because:

```
function addSeconds (dirtyDate, amount) {
  var date = parse(dirtyDate)

  console.log('dirtyDate ', dirtyDate)
  console.log('parsedDate', date)
  console.log('amount', amount)

  date.setSeconds(date.getSeconds() + amount)

  console.log('after transformation', dirtyDate, date, amount)

  return date
}
```

is broken, result:

```
dirtyDate 2016-12-06T12:49:46.664Z
parsedDate 2016-12-06T12:49:46.664Z
amount 60
after transformation 2016-12-06T14:06:40.664Z
```

Where the expected result would be `2016-12-06T12:50:46.664Z`. This in turn causes `token.expired()` to trigger false positives, which in turn causes refresh tokens not to be generated. I know this is a problem of the dependency, but maybe a dependency update would already help?

**Comment by arekkas** [comment]
Ah, the problem is that `amount` is a string, so it's not actually `60` but `"60"`.

**Comment by jonathansamines** [comment]
That is likely because your token response is returning the `expires_in` property as a string. See https://github.com/lelylan/simple-oauth2/blob/master/lib/client/access-token.js#L25

**Comment by scaryguy** [comment]
In my case the API returns a string too. So isn't it better if we put a casting there and make sure that `expires_in` is an Integer?

**Comment by arekkas** [comment]
I resolved this in the library that was causing it. However, it might still be smart to have a `parseInt` somewhere?

**Comment by arekkas** [comment]
Because if it happens, the bug is annoying to debug imho :D

**Comment by jonathansamines** [comment]
@arekkas will fix as soon as I can. A PR would be welcome though.
