### ISSUE TITLE
jwt support - enhancement

### ISSUE THREAD

**Issue by noenthu** [lelylan/simple-oauth2#122]
Trying to use the library to authenticate users against Visual Studio which uses jwt bearer token and getting an error that grant_type must be jwt-bearer
The format is as
```
POST https://app.vssps.visualstudio.com/oauth2/token
        ?client_assertion_type=urn:ietf:params:oauth:client-assertion-type:jwt-bearer
        &client_assertion={AppSecret}
        &grant_type=urn:ietf:params:oauth:grant-type:jwt-bearer
        &assertion={authorization code}
        &redirect_uri={callbackUrl}
```

Appears that grant_type is fixed at authorization_code

**Comment by jonathansamines** [comment]
Hi @noenthu I dont really know  the JWT specification, nor I have used it before. PRs are welcome though.
