### ISSUE TITLE
React Native compatibility ?

### ISSUE THREAD

**Issue by nicolasthy** [lelylan/simple-oauth2#125]
Hello,

I was wondering if this package works on React Native? I've installed it but get the following error:
![screen shot 2017-02-21 at 16 31 35](https://cloud.githubusercontent.com/assets/4039090/23171641/55435d26-f853-11e6-876d-c051a8b4fae3.png)

I tried adding the `url` package to my project but it still doesn't work. Did I miss something or does it not work with React Native?

Looks like I need node core modules that are not supported in React Native...
Anyone know a workaround ? Tried this with no success: https://github.com/mvayngrib/rn-nodeify

**Comment by jonathansamines** [comment]
Well, I really dont have any experience with react native. I dont know in which kind of environment it runs to determine if that could be the cause. However if as you said is related at some modules not being able to loaded in react-native, there is not much we can do about it. We only support and test through the node environment. 

I would give browserify a try and see if it works by using the native modules replacement.

**Comment by Srywards** [comment]
UP, same issue for me @nicolasthy did you find something for this ?
