### ISSUE TITLE
Support for Self Signed Certificates

### ISSUE THREAD

**Issue by cwoodworth** [lelylan/simple-oauth2#126]
Is it possible to disable SSL validation for the oauth2.clientCredentials.getToken() function?  I am receiving the following error when requesting a token, and I believe this may be due to self signed certificates in my environment.

error.message:  'unable to verify the first certificate'

Sample Code:
```
    oauth2.clientCredentials.getToken(tokenConfig, function(error, result){
        if(error){
            console.log('Failed to get access token', error.message);
            deferred.resolve(null);
        }
```

**Comment by jonathansamines** [comment]
As far as I remember, there is a couple of ways to do so. 

1. Disabling it globally by using the `NODE_TLS_REJECT_UNAUTHORIZED` environment variable. Even though this method is discouraged (your are ignoring the underlying problem), it is useful for development environments.
2. Passing the `rejectUnauthorized` option to the https [request options](https://nodejs.org/api/https.html#https_https_request_options_callback). This cannot be done directly, but `request-js` supports the same feature by using the [agentOptions](https://github.com/request/request#requestoptions-callback) option. To implement this, simple-oauth2 allows to pass the `http` options which are directly passed to the underlying `request-js` library.

Let me know if any of the solutions above works for you.

**Comment by cwoodworth** [comment]
The Global disable worked for me as an interim until I can try option 2.

**Comment by jagradang** [comment]
I am trying to get option 2 working but can't seem to figure out how to get option 2 working.  Did you ever get this working with option 2?
