### ISSUE TITLE
URL is wrong http://lelylan.github.com/simple-oauth2/

### ISSUE THREAD

**Issue by kamoljan** [lelylan/simple-oauth2#127]
Hi

The URL is wrong or outdated http://lelylan.github.com/simple-oauth2/

Cheers

**Comment by andreareginato** [comment]
@jonathansamines any idea about this? The link is correct to me

**Comment by jonathansamines** [comment]
I really have no idea about this, seems like the underlying service got out of sync from this repository github page branch? I can´t check it because I dont have access to it.

**Comment by chovy** [comment]
blank page for me.

**Comment by andreareginato** [comment]
Fixed. It was a wrong reference to the document up docs generation

**Comment by jonathansamines** [comment]
Great, seems updated also, thanks!
