### ISSUE TITLE
Unhandled rejection Error: Bad Request

### ISSUE THREAD

**Issue by cucamacuca** [lelylan/simple-oauth2#135]
Hi I'm trying to use the following example but the output is:
Unhandled rejection Error: Bad Request

The snippet:

```
const credentials = {
  client: {
    id: 'id',
    secret: 'secre',
  },
  auth: {
    tokenHost: 'https://api.instagram.com',
    tokenPath: '/oauth/access_token',
    authorizePath: '/oauth/authorize',
  },
};

const oauth2 = require('simple-oauth2').create(credentials);

const tokenConfig = {
  username: 'user',
  password: 'password' 
};

// Callbacks
// Save the access token
oauth2.ownerPassword.getToken(tokenConfig, (error, result) => {
  if (error) {
    return console.log('Access Token Error', error.message);
  }

  const token = oauth2.accessToken.create(result);
});

// Promises
// Save the access token
oauth2.ownerPassword
  .getToken(tokenConfig)
  .then((result) => {
    const token = oauth2.accessToken.create(result);

    return token;
  });
```

Any tips?

**Comment by jonathansamines** [comment]
Hi, sorry for the late response. That probably means you oauth server doesn´t like what this library is sending with the token  request. To see the reason, try enabling the debuging mode (DEBUG=*simple-oauth2* <your node command>) and take a look at the response body in [this message](https://github.com/lelylan/simple-oauth2/blob/master/lib/core.js#L20)

Hope that helps

**Comment by jonathansamines** [comment]
Closing due inactivity.

**Comment by jondcallahan** [comment]
FYI I was able to fix this issue by adding 
```javascript
...
options: {
      authorizationMethod: 'body',
},
...
```
to the object passed in to `OAuth2.create`
