### ISSUE TITLE
CORS issue with res.redirect(authorizationUri)

### ISSUE THREAD

**Issue by therealgilles** [lelylan/simple-oauth2#136]
I am getting CORS issue with res.redirect(authorizationUri). I would think it would be a common issue as oauth2 redirect seems to usually be done in the browser by changing window.location. Kidn of curious why noone has mentioned it before here. Any enlightening advice would be appreciated.

**Comment by jonathansamines** [comment]
Not completely sure what you mean by this. What "res.redirect" usually does, is to perform an HTTP redirection which the browser usually follows. Do you have any reproducible example to which I can take a look at?

**Comment by therealgilles** [comment]
Okay let me explain:

The redirect goes from the current (express) server to the oauth2 server. If the oauth2 server is not setup to allow cross-origin requests, the browser will block the redirect and report a CORS error. The error looks like this in Safari:

Failed to load resource: Cross-origin redirection to https://<oauth2_server>/oauth/authorize?redirect_uri=<redirect_uri>&response_type=code&client_id=<client_id> denied by Cross-Origin Resource Sharing policy: Origin http://localhost:3000 is not allowed by Access-Control-Allow-Origin.

Other libraries like redux-oauth work around this issue using a popup window. The oauth2 server authorize page is open in the popup from the front-end app. If using authorization code grant type, after authorization, the popup location (and hence the code) is captured by the front-end app before the popup is closed, and then the code can be sent to the server to then get the token with an ajax post request.

Another way to work around the issue is to send the authorize url to the front-end app and make the front-end app do a window.location.assign(authorizeUrl), which is not subject to CORS.

This issue most likely does not occur with oauth2 servers like github's, because they are configured to access CORS. My oauth2 server runs on a hosted wordpress site, and I do not have control over the apache server, which has CORS disabled.

**Comment by jonathansamines** [comment]
@therealgilles I did not even knew CORS restrictions were applied to normal browser requests/redirection process. However a workaround could be to return the redirection url instead as part of the resource response, and then performing the redirection at the client side with window.location or even with a window popup. Sorry for not having any other advise, but haven´t deal with those problems myself before.

Hope this helps you.

**Comment by therealgilles** [comment]
I tried both the popup and the redirection from the client side. The popup seemed awkward so I chose the redirection.

**Comment by suhadev** [comment]
Do we have any solution for this??

**Comment by jonathansamines** [comment]
@suhadev Have you tried any of the solutions listed above? This is not actually a problem of this library, just how http works in browsers environments.

**Comment by suhadev** [comment]
@jonathansamines Thanks for your quick reply. I tried sending authorizationuri back to the client and opened the url using window .open() and it works, but my problem is I need to know if my authorization is successful or not and have to update the UI based on that. When I get authorization URI as response to the request I send, how can I know if authorization is successful or not in client side. I can not treat recieving authorizationURI as successfull authentication

**Comment by NoelToy** [comment]
Am facing same issue. Is there any solution for this issue?
