### ISSUE TITLE
Please tell me the reason.

### ISSUE THREAD

**Issue by flyerui** [lelylan/simple-oauth2#144]
Error {stack: "Error: Bad Request", name: "Error", status: 400 …}
context:Object {error: "invalid_grant", error_description: "Invalid authorization code: VWX0e2"}
error:"invalid_grant"
error_description:"Invalid authorization code: VWX0e2"
__proto__:Object {hasOwnProperty: function hasOwnProperty() { [native code] }, constructor: function Object() { [native code] }, toString: function toString() { [native code] } …}
message:"Bad Request"
name:"Error"
stack:"Error: Bad Request"
status:400
__proto__:Error

The following is a reference code

'use strict';

const express = require('express');
const simpleOauthModule = require('./../');

const app = express();
const oauth2 = simpleOauthModule.create({
  client: {
    id: 'acme',
    secret: 'acmesecret',
  },
  auth: {
    tokenHost: 'http://cas.qa.aukeyit.com',
    tokenPath: '/oauth/token',
    authorizePath: '/oauth/authorize',
  },
});

// Authorization uri definition
const authorizationUri = oauth2.authorizationCode.authorizeURL({
  redirect_uri: 'http://localhost:3000/callback',
  scope: 'notifications',
  state: 'OJNS2t',
});

// Initial page redirecting to Github
app.get('/auth', (req, res) => {
  console.log(authorizationUri);
  res.redirect(authorizationUri);
});

// Callback service parsing the authorization token and asking for the access token
app.get('/callback', (req, res) => {
  const code = req.query.code;
  const options = {
    code,
    redirect_uri: 'http://localhost:3000/callback',
  };
  debugger;
  oauth2.authorizationCode.getToken(options, (error, result) => {
    if (error) {
      console.error('Access Token Error', error.message);
      return res.json('Authentication failed');
    }

    console.log('The resulting token: ', result);
    const token = oauth2.accessToken.create(result);

    return res.status(200).json(token);
  });
});

app.get('/success', (req, res) => {
  res.send('');
});

app.get('/', (req, res) => {
  res.send('Hello<br><a href="/auth">Log in with Github</a>');
});

app.listen(3000, () => {
  console.log("Express server started on port 3000"); // eslint-disable-line
});

![image](https://user-images.githubusercontent.com/15017367/29992743-73fc06b8-8fd5-11e7-9b8d-b12b3b4d6cbd.png)
![image](https://user-images.githubusercontent.com/15017367/30025857-04a457c8-91ad-11e7-8dc8-619f0bd372f0.png)

**Comment by glmagalhaes** [comment]
Can you post the request you were using?

**Comment by flyerui** [comment]
'use strict';

const express = require('express');
const simpleOauthModule = require('./../');

const app = express();
const oauth2 = simpleOauthModule.create({
  client: {
    id: 'acme',
    secret: 'acmesecret',
  },
  auth: {
    tokenHost: 'http://cas.qa.aukeyit.com',
    tokenPath: '/oauth/token',
    authorizePath: '/oauth/authorize',
  },
});

// Authorization uri definition
const authorizationUri = oauth2.authorizationCode.authorizeURL({
  redirect_uri: 'http://localhost:3000/callback',
  scope: 'notifications',
  state: 'OJNS2t',
});

// Initial page redirecting to Github
app.get('/auth', (req, res) => {
  console.log(authorizationUri);
  res.redirect(authorizationUri);
});

// Callback service parsing the authorization token and asking for the access token
app.get('/callback', (req, res) => {
  const code = req.query.code;
  const options = {
    code,
    redirect_uri: 'http://localhost:3000/callback',
  };
  debugger;
  oauth2.authorizationCode.getToken(oauth2, (error, result) => {
    if (error) {
      console.error('Access Token Error', error.message);
      return res.json('Authentication failed');
    }

    console.log('The resulting token: ', result);
    const token = oauth2.accessToken.create(result);

    return res.status(200).json(token);
  });
});

app.get('/success', (req, res) => {
  res.send('');
});

app.get('/', (req, res) => {
  res.send('Hello<br><a href="/auth">Log in with Github</a>');
});

app.listen(3000, () => {
  console.log("Express server started on port 3000"); // eslint-disable-line
});

// Credits to [@lazybean](https://github.com/lazybean)

**Comment by flyerui** [comment]
Hello, I have modified again, please help me to check the reason, thank you!

**Comment by jonathansamines** [comment]
@flyerui Sorry for the late response, in case you are still working on it, seems from the error message that the redirectURL you are configuring with this library doesn't match the one configured when you created your client credentials.

Hope that helps you.
