### ISSUE TITLE
how can I change "expires_at" key with "expires_in" so that it work fine for me?

### ISSUE THREAD

**Issue by AbdulHaye** [lelylan/simple-oauth2#145]
Is there any way except modifying the whole library for changing key "expires_at" with "expires_in"

**Comment by jonathansamines** [comment]
@AbdulHaye do you mind to better explain what you mean by this? what is your use case?

**Comment by AbdulHaye** [comment]
Sorry to interrupt,
Now it is working fine for me :)
Thanks

**Comment by jonathansamines** [comment]
Great to hear, will close the issue then :)
