### ISSUE TITLE
Client id and secret must be urlencoded according to spec (RFC6749)

### ISSUE THREAD

**Issue by arekkas** [lelylan/simple-oauth2#148]
> Clients in possession of a client password MAY use the HTTP Basic
authentication scheme as defined in [RFC2617] to authenticate with
the authorization server. The client identifier is encoded using the
"application/x-www-form-urlencoded" encoding algorithm per
Appendix B, and the encoded value is used as the username; the client
password is encoded using the same algorithm and used as the
password. - [Source](https://tools.ietf.org/html/rfc6749#section-2.3.1)

This is currently not the case.

**Comment by jonathansamines** [comment]
@arekkas I haven't used that workflow myself, and nobody has reported errors with this yet. Fee free to open a PR if you are currently encountering issues with this, or point me to which utility are you referring to.

**Comment by arekkas** [comment]
It's as easy a wrapping https://github.com/lelylan/simple-oauth2/blob/master/index.js#L13-L14 with query escape. I'll draft up a PR later.

**Comment by jonathansamines** [comment]
@arekkas This should be fixed at 1.5.0. Please let me know if that works.

**Comment by wallymathieu** [comment]
Well, there might be some trouble with using access tokens together with [IdentityServer4](https://github.com/IdentityServer/IdentityServer4). I think we had to downgrade to 1.3.0 version of this lib in order to be able to use things like `+` or `&`.

**Comment by jonathansamines** [comment]
@wallymathieu If I understand correctly, it is an issue with IdentifyServer4, which does not comply with the RFC 6749. Is that the case? If not, would you help me understand where the issue lies?

**Comment by wallymathieu** [comment]
Yes, I asked the IdentityServer guys. The bug is in IdentityServer4 (and perhaps in 3 as well https://github.com/lelylan/simple-oauth2/issues/167 ).

**Comment by arekkas** [comment]
> Yes, I asked the IdentityServer guys. The bug is in IdentityServer4 (and perhaps in 3 as well #167 ).

It's a bug on their side.
