### ISSUE TITLE
Consider upgrading your debug version to fix ReDoS attack vector

### ISSUE THREAD

**Issue by Nargonath** [lelylan/simple-oauth2#151]
It is all explained in your dependencies checker: https://nodesecurity.io/advisories/debug_regular-expression-denial-of-service

`debug` version should be upgraded to `^3.1.0` instead of `^3.0.1`.

**Comment by malkaviano** [comment]
Actually, consider removing it, along with dependencies we don't really need on our projects to make simple-oauth2 work.

Tx.

**Comment by Nargonath** [comment]
Yeah that would be another solution. I've never used that package so I couldn't really argue about its usefulness or not. If it is up to date that would be enough for me.
