### ISSUE TITLE
Not able to set User-Agent  in headers

### ISSUE THREAD

**Issue by andreasviklund** [lelylan/simple-oauth2#163]
According to the documentation you could set global options to the internal http library (request-js), in the credentials object.

I am trying to set a custom User-Agent text string and my code looks like this:

`const credentials = {
  client: {
    id: '<CLIENT_ID>',
    secret: '<CLIENT_SECRET>'
  },
  http: {
    headers: {'User-Agent': 'My User Agent String'}
  }
  ,
  auth: {
    tokenHost: 'https://www.host.com',
    tokenPath: '/api/oauth2/v1/token',
    authorizePath: '/api/oauth2/v1/auth',
  }
};`

But it doesn´t seem to work. When I look at the request header in Fiddler it has not changed. Any suggestions?

**Comment by jonathansamines** [comment]
Hi, sorry to hear is not working for you. I would suggest starting your application with the following env variable:

```bash
  DEBUG="simple-oauth2:main" <command to start app>
```

That will allow you which settings are actually being sent to the request module. Knowing the library version are you using would also be useful.

**Comment by jonathansamines** [comment]
Closing due inactivity.
