### ISSUE TITLE
Add documentation to use an API

### ISSUE THREAD

**Issue by Gottox** [lelylan/simple-oauth2#166]
Thanks for this awesome library!

I'm using simple-oauth2 in conjunction with node-oauth2-server and successfully used this library to authenticate with the server. At the moment I'm trying to use the accessToken to query the actual API.

It would be great to have an example how to configure the HTTP client to query an OAuth2 secured server using an accessToken object.

**Comment by mbhildebrand** [comment]
Hi There!  This is a great library for use in my JavaScript client.  Has there been any testing using the IdentityServer3 Server side OAuth2?  I'm planning on using this library for that situation.

**Comment by jonathansamines** [comment]
@Gottox @mbhildebrand We don't have examples of authorized calls, but the existing github example could be modified to include an example for that, a pull request would be welcome with that addition ;)

**Comment by jonathansamines** [comment]
@Gottox @mbhildebrand  Feel free to submit a PR if you want to contribute with an example for IdentityServer3.
