### ISSUE TITLE
Tested with IdentityServer3?

### ISSUE THREAD

**Issue by mbhildebrand** [lelylan/simple-oauth2#167]
Hi There! This is a great library for use in my JavaScript client. Has there been any testing using the IdentityServer3 Server side OAuth2? I'm planning on using this library for that situation.

**Comment by jonathansamines** [comment]
@mbhildebrand Besides the github example (https://github.com/lelylan/simple-oauth2/tree/master/example), we don't test this library with any specific authorization server. A PR with an example specific for this provider would be welcome though.

**Comment by rolpal** [comment]
I use it in node.js with our IS3 server and OAuth2 and it works fine (until last commit, see comment) when it broke. But I have fixed it by changing the utils.js to remove the URL encoding of clientId and clientSecret.

**Comment by jonathansamines** [comment]
@rolpal Please see referenced issues. This is an issue on IdentityServer side
