### ISSUE TITLE
Client Credentials and Invalid Scope

### ISSUE THREAD

**Issue by mbhildebrand** [lelylan/simple-oauth2#168]
Hi -
I'm using your great library wanting to get an access token using Client Credentials flow.  The client's id and secret are set, but the error I'm getting is this:

    simple-oauth2:main Checking response body {"error":"invalid_scope"} +281ms

Where in the configuration do I specify the 'scope'?  Is there other documentation I missed?

Thanks,
Michael

**Comment by jonathansamines** [comment]
@mbhildebrand Scope can be specified at the  "getToken" call for any of the available grants, example:

```js
oauth2.ownerPassword.getToken({ scope: 'your-valid-scope' });
```

See: https://github.com/lelylan/simple-oauth2#client-credentials-flow

It is a non-documented behavior, a PR would be welcome to document it :)

**Comment by jonathansamines** [comment]
@mbhildebrand  I already documented this. Feel free to re-open if the solution above didn't work for you.
