### ISSUE TITLE
405 not found

### ISSUE THREAD

**Issue by rainitesh** [lelylan/simple-oauth2#169]
I am trying the Password Credentials Flow and keep getting this error.

It should be a POST method but my default it uses a GET method. Has anyone faced this issue?

**Comment by jonathansamines** [comment]
@rainitesh Do you mind to elaborate a bit more? How are you using the library? What is the actual http request sent vs what your api requires?

**Comment by jonathansamines** [comment]
Closing due inactivity. @rainitesh Please re-open if you can provide additional information to help solving the issue.
