### ISSUE TITLE
How to delete old tokens, is their any method to prune old token when create new token or one token at a time for a user?

### ISSUE THREAD

**Issue by prashantidealittechno** [lelylan/simple-oauth2#173]

**Comment by jonathansamines** [comment]
@prashantidealittechno If the OAuth2 RFC describes a way to do that, do you mind to point me out to where that is described? A pull request adding this is also welcome.

**Comment by jonathansamines** [comment]
@prashantidealittechno You can use the `accessToken.revoke()` to manually invalidate a token before creating a new one.

**Comment by jonathansamines** [comment]
Feel free to reopen this issue if the above suggestion doesn't work for you.
