### ISSUE TITLE
Failed to minify the code when using create-react-app build

### ISSUE THREAD

**Issue by ivarbergman** [lelylan/simple-oauth2#183]
Hi! Have problems with this package (or some of its dependencies) when using the `create-react-app build` scipts.

To reproduce:

Create a new `create-react-app` project.

    $ npx create-react-app my-app

Add `simple-oauth2`

    $ yarn add simple-oauth2

Add the import statement in the `src/App.js` file. 

    import oauth2 from 'simple-oauth2';

And finally build

    $ yarn build

This will produce the following error:

    Creating an optimized production build...
    Failed to compile.
    
    Failed to minify the code from this file: 
    
     	./node_modules/hoek/lib/index.js:33 
    
    Read more here: http://bit.ly/2tRViJ9
    
    error An unexpected error occurred: "Command failed.
    Exit code: 1

**Comment by jonathansamines** [comment]
@ivarbergman Sorry to hear this module is not working for you. But it is not intended for browser usage. We depend on some libraries which are explicitly designed for client-side usage.

What kind of use-case on client side apps do you have in mind?

**Comment by ivarbergman** [comment]
Hi @jonathansamines 
Thanks for response, and you are absolutely right, I really don't need simple-oauth2 in the client bundle of my app.

What I did was to use the `authorizeURL` to generate the authorization Uri for the client. (Leaving out the `secret` from the `credentials`.) But I should of course handle this redirect on the server-side instead.

You may close this issue.
Cheers!
