### ISSUE TITLE
1.5.2 is published as latest

### ISSUE THREAD

**Issue by vsmori** [lelylan/simple-oauth2#190]
Hello,

1.5.2 version is published as latest. Is this correct?

https://www.npmjs.com/package/simple-oauth2

Thanks,
Vitor

**Comment by codeheroics** [comment]
Thank you so much for opening this issue, I would have lost all day if I hadn't found it and realized I was not using version 2.x!

**Comment by jonathansamines** [comment]
Sorry for the confusion, will try to update 2.0.0 as latest as soon as I am able to.
