### ISSUE TITLE
Syntax error in Internet Explorer.

### ISSUE THREAD

**Issue by lukasbach** [lelylan/simple-oauth2#191]
When trying to use the package in a react app, it crashes when using the oauth2.create method. The problem only occurs on Internet Explorer (I am using v11) and only when calling the oauth2.create method. On Chrome or if not using this method, no errors occur.

The error message is:
`SCRIPT1003: Expected ':'
app.af31c19e4cf366a1985f.js (3621,1)`

The affected line unfortunately only includes the compiled package code, so I am not sure where exactly the problem comes from.
![image](https://user-images.githubusercontent.com/4140121/40007666-b59760be-579d-11e8-97a1-73cc907b914b.png)

**Comment by jonathansamines** [comment]
@lukasbach Sorry for the late response. Unfortunately this module is not designed to run in the browser, mainly because we have some dependencies which use Node only features. Which part of the module are you trying to use in the browser?

**Comment by lukasbach** [comment]
I have been using the methods

oauth2.authorizationCode.authorizeURL
oauth2.authorizationCode.getToken

I have reimplemented most of the logic using native HTTP requests, so if you don't plan on bringing the logic to the browser, it is not that problematic for me.

**Comment by lukasbach** [comment]
Yes, I assume my application use case was more a corner case. Marking this as closed.
