### ISSUE TITLE
Dynamic clientId

### ISSUE THREAD

**Issue by crung** [lelylan/simple-oauth2#193]
Hi,

I'm implementing a multi-tenant service that relies on auth code flow with a provider (Auth0). Every tenant has their own set of credentials and subdomain.

The problem I'm having is that most if not all clients such as this require you to define your credentials up front with a constructor. The credentials from then on cannot be changed and I'm forced to instantiate a new copy with each request. 

Are there any plans for this library to work in a front-ended fashion where you can specify the credentials at the point of authenticating rather than as an initializer?

**Comment by jonathansamines** [comment]
@crung Sorry for the delay. I am not familiar with how those authentication systems works. If you have a proposal in mind I am open to suggestions.

**Comment by jonathansamines** [comment]
Closing due inactivity.
