### ISSUE TITLE
offload access_token.refresh() to client type

### ISSUE THREAD

**Issue by leroy0211** [lelylan/simple-oauth2#202]
You better offload the `accessToken.refresh()` to the client-type. Right now you are assuming that every token can be refreshed with a `refresh_token`. 

`client_credentials` tokens can not be refreshed like that, they have to be recreated like the first token you get. 

However I like your `refresh()` method, so I would like to see that `client_credentials` can be "refreshed" the same way.

**Comment by jonathansamines** [comment]
@leroy0211 How the `refresh` method for the client credentials flow would look like? What would it do internally that is different from the refresh method for other grant types?

**Comment by leroy0211** [comment]
Well the client_credentials flow does not add a refresh_token to the response [See the spec, section 4.4.3](https://tools.ietf.org/html/rfc6749#section-4.4.3). 

> A refresh token SHOULD NOT be included.

That is because when the client credentials access_token is expired, the client should recreate a new access token the way it did before. The client_credentials flow is a "userless" flow, just to give a server access to the resource server.

**Comment by jonathansamines** [comment]
Decided to not implement this, as it supporting this can be confusing for people to familiar with how the client_credentials grant type works.

**Comment by leroy0211** [comment]
Sad to see this is not going to be changed, because the client_credentials grant type should never be refreshed with a refresh_token. It should be re-obtained.

**Comment by jonathansamines** [comment]
Finally decided to tackle this one. Will implement by offloading the access token wrapper from the refresh token process.
