### ISSUE TITLE
Connecting to Freshbooks API?

### ISSUE THREAD

**Issue by tudorific** [lelylan/simple-oauth2#203]
Hi,

I am trying to connect to the Freshbooks API using simple-oauth2 and am having quite a lot of issues, not really sure if its related to this library or how I am trying to connect. Any help would be appreciated because I have no idea where to go next.

On the API page it mentions specifying 'Api-Version' and 'Authorization' (Bearer) which I am not sure how to specify in the library parameters. Could this be causing issues?

https://www.freshbooks.com/api/start

Here is how my code looks: 
```

const oauth2 = simpleOauthModule.create({
    client: {
        id: process.env.CLIENT_ID,
        secret: process.env.CLIENT_SECRET,
    },
    auth: {
        tokenHost: 'https://api.freshbooks.com',
        tokenPath: '/auth/oauth/token',
        //authorizePath: 'https://my.freshbooks.com/service/auth/oauth/authorize',
        authorizePath: 'https://my.freshbooks.com/service/auth/integrations/sign_in',
    },
    options: {
        bodyFormat: 'json',
        authorizationMethod: 'body',
    },
});

//authorization uri definition
const authorizationUri = oauth2.authorizationCode.authorizeURL({
    redirect_uri: 'https://localhost/callback',
    //scope: 
    //state:
});

//initial page redirecting to freshbooks
router.get('/auth', function(req, res) {
    console.log('Inside /auth');
    console.log(authorizationUri);
    res.redirect(authorizationUri);
});

//callback service parsing the authorization token and asking for access token
router.get('/callback', async (req, res) => {
    console.log('Inside /callback');
    const code = req.query.code;
    const options = {
        code,
    };

    try {
        const result = await oauth2.authorizationCode.getToken(options);
        console.log('The resulting token: ', result);

        return res.status(200).json(token);
    } catch(error) {
        console.error('Access token error', error.message);
        return res.status(500).json('Authentication failed');
    }
});
```

There are no errors thrown, but when I click my button to authenticate it takes me to the Freshbooks login page...this is OK, I type in my username and password and click Sign In. At this point i expect to hit the 'callback' route and see my console.log at the very least but nothing happens. The sign in page appears again and nothing is printed to the console. I am 100% sure the username and password are correct.

Any ideas what I am doing wrong? 

Thanks!

**Comment by jonathansamines** [comment]
Closing due inactivity. Feel free to re-open with more information if your issue persist.
