### ISSUE TITLE
AssertionError in joi due to API update

### ISSUE THREAD

**Issue by mattdavis90** [lelylan/simple-oauth2#204]
The joi library was updated to v13.5.0 today and this has caused the following error in simple-oauth2
```
AssertionError [ERR_ASSERTION]: options contain unknown keys: 0,1
    at internals.String.uri (/data/node_modules/joi/lib/types/string/index.js:286:18)
    at Object.<anonymous> (/data/node_modules/simple-oauth2/index.js:22:42)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18
```
I'm happy to create a PR to fix this

**Comment by piuccio** [comment]
I just tried to update to `simple-oauth2` and I'm getting the same error. I guess it would be great if you could create a PR, speed up things 😀

**Comment by piuccio** [comment]
Oh didn't notice you did it already in #205

**Comment by AllenBird** [comment]
waitting for the new version

**Comment by freddygymlib** [comment]
+1

**Comment by lloydst** [comment]
had to change it back too v1.5.2 for it to work again in my project

**Comment by sbyrne-sugarcrm** [comment]
+1 ran into this problem myself.

**Comment by andrewtanner1987** [comment]
Looks like this has been fixed as the PR was merged in a couple of hours ago. How long until this is available via npm, please? Forgive me if this is a naive question, I'm quite new to working with node/npm.

**Comment by mattdavis90** [comment]
Hopefully soon. One of the project maintainers needs to bump the version and push to npm.

@jonathansamines Do you have a rough idea of when you plan to release? Thanks

**Comment by andrewtanner1987** [comment]
Thank you. I didn't know if this was an automated process.

**Comment by Gorenjai** [comment]
+1 been scratching my head for an hour to figure out what was happening..

**Comment by tony-gutierrez** [comment]
+1 this started appearing in my logs recently.

**Comment by william-j-lewis** [comment]
If you need a quick fix, you can edit the file "index.js" (line 22). See if this does the trick.
Before:
![image](https://user-images.githubusercontent.com/37314098/43651219-ca6500f8-970f-11e8-8a90-2e5bed3bfcd1.png)
After:
![image](https://user-images.githubusercontent.com/37314098/43651290-f27add38-970f-11e8-883e-2e510aaf52b8.png)

**Comment by Gorenjai** [comment]
@william-j-lewis i've had to do that unfortunately.. hopefully can upgrade in the next few days..

**Comment by tony-gutierrez** [comment]
Can someone get us an update??

**Comment by tony-gutierrez** [comment]
jsut change your package.json to the older joi and release a version already!

**Comment by andrewtanner1987** [comment]
They've fixed it but it's not been pushed to npm yet. Remember, this is
open source software so please be patient.

**Comment by tony-gutierrez** [comment]
Ah, so they just arent doing anything with npm, or npm takes time?

**Comment by tony-gutierrez** [comment]
@jonathansamines, @andreareginato ?

**Comment by jonathansamines** [comment]
Sorry for the delay. simple-oauth2@2.2.1 was published with the fix. Please let me know if that fix the problem.

**Comment by MicroDroid** [comment]
That did work.

**Comment by william-j-lewis** [comment]
Thank you @jonathansamines!
