### ISSUE TITLE
oauth2.accessToken is undefined

### ISSUE THREAD

**Issue by KidA001** [lelylan/simple-oauth2#214]
I'm trying to check if my access token is expired so I can refresh. Per the instructions under [Helpers#AccessToken](https://github.com/lelylan/simple-oauth2#access-token-object) is says to create a accessToken wrapper with `oauth2.accessToken.create(tokenObject);`

I have 
```javascript
import oauth2 from "simple-oauth2";
...
...

let accessToken = oauth2.accessToken.create(_accessToken);
...
```

And I get an error `Cannot read property 'create' of undefined`

When I inspect, there is no function `oauth2.accessToken`, so it returns `undefined`. What is the correct syntax?

**Comment by KidA001** [comment]
It seems like `oauth2.accessToken` is undefined because this is a new session from when I originally received the token.

These tokens expire after X hours, how do I re-initialize the oauth2 object and pass it my token to check if it's expired and refresh?

**Comment by jonathansamines** [comment]
@KidA001 Seems like `oauth2` is undefined. Does it work if you use `oauth.default.accessToken.create`?

**Comment by jonathansamines** [comment]
Closing due inactivity. Please feel free to open if you are still experiencing the issue.
