### ISSUE TITLE
Unable to specify scope when refreshing token

### ISSUE THREAD

**Issue by Javaman44** [lelylan/simple-oauth2#215]
In some Oauth implementation  we could specify scope when refreshing token (https://www.oauth.com/oauth2-servers/access-tokens/refreshing-access-tokens/)

For example:
"scope (optional)
The requested scope must not include additional scopes that were not issued in the original access token. Typically this will not be included in the request, and if omitted, the service should issue an access token with the same scope as was previously issued."

Could you add this option ?

Regards

**Comment by Javaman44** [comment]
Ok i see in the source code that is possible
` /**
    * Refresh the access token
    * @param  {Object} params An optional argument for additional API request params.
    */
async refresh(params) {`

It could be nice to include some info in the README

Regards

**Comment by jonathansamines** [comment]
@Javaman44 You are right, that is not documented. PR to improve the documentation are welcome though :)

**Comment by danielo515** [comment]
I guess that param applies to all the query params right?
Would it be possible to specify that params on the creation of the oauth object? So all the subsequent requests (including create auth url and refresh token) include the same params?

**Comment by jonathansamines** [comment]
@danieladams456 Right now it is not possible out of the box. However if you wrap the library, that shouldn't be that hard.

**Comment by jonathansamines** [comment]
Solved by #257
