### ISSUE TITLE
grant_type password is not working

### ISSUE THREAD

**Issue by harshkothari410** [lelylan/simple-oauth2#219]
grant_type password is not working. Mostly its wreck issue. But still its not working.

**Comment by jonathansamines** [comment]
@harshkothari410 How is this library exactly not working you? A reproduction would be greatly appreciated

**Comment by koyal-mittal** [comment]
@harshkothari410 did you find a solution or a workaround? I'm facing the same issue

**Comment by jonathansamines** [comment]
@koyal-mittal Unless detailed information or a reproduction example is provided. I won't be able to provide any help.

**Comment by jonathansamines** [comment]
Feel free to reopen with more information if you are still experiencing this issue
