### ISSUE TITLE
Set a timeout for token retrieval

### ISSUE THREAD

**Issue by airbone42** [lelylan/simple-oauth2#220]
Is it possible to set a timeout for the token request in the case that the oauth-server is currently not available or responding?

**Comment by jonathansamines** [comment]
You may want to try with the [http option](https://github.com/lelylan/simple-oauth2#options). You cannot set the option, just for the token request though.

**Comment by jonathansamines** [comment]
@airbone42 Will close this issue due inactivity. Please feel free to reopen if you are still experiencing this issue or the provided help didn't work out.

**Comment by jonathansamines** [comment]
@airbone42 Will close this issue due inactivity. Please feel free to reopen if you are still experiencing this issue or the provided help didn't work out.

**Comment by jonathansamines** [comment]
Solved by #270.
