### ISSUE TITLE
Authorization URI callback not being built correctly

### ISSUE THREAD

**Issue by sn0rcha** [lelylan/simple-oauth2#222]
Hey there,

I've got an issue with the following code:

```
const authorizationUri = oauth2.authorizationCode.authorizeURL({
            redirect_uri: `https://someurl.com/callback`,
            scope: 'some_scope',
            state: 111222333
        });
````
The callback URL is being returned as:

```https://someurl.com/callback&scope=some_scope&state=111222333```

This is incorrect as the first query variable should be "?" not "&".

Is there something I'm doing wrong?

Cheers,
Ben

**Comment by jonathansamines** [comment]
Given the current logic doesn't seems possible to have that error. Which version of the library are you using?

**Comment by sn0rcha** [comment]
2.2.1

**Comment by sn0rcha** [comment]
Sorry my bad I was reading the URL wrong - Oops!!
