### ISSUE TITLE
Await is only valid in async function

### ISSUE THREAD

**Issue by wbaridon** [lelylan/simple-oauth2#223]
Hi everyone,
I tried to implement the Client Credentials Flow like the readme but I have a syntax error. 
' await is only valid in async function ' 

```
  try {
        const result = await oauth2.clientCredentials.getToken(tokenConfig);
        const accessToken = oauth2.accessToken.create(result);
      } catch (error) { 
         console.log('Access Token Error', error.message); 
     }
```

**Comment by VictorioBerra** [comment]
Copy and pasted right off the README. **Same issue!!!!!**

**Comment by shepsii** [comment]
read up on this here guys: https://javascript.info/async-await

**Comment by VictorioBerra** [comment]
So it's not working because we're in top level? I think the readme should wrap the example.

**Comment by shepsii** [comment]
I think it’s not unreasonable for a readme to assume the developer knows how to translate async code to standard promises

If you’re working with JavaScript and you don’t know how to do that, you need to read up on it.

**Comment by VictorioBerra** [comment]
"Here's some sample code, oh by the way it doesn't work. But you should know that, you're a developer aren't you?"

It is not unreasonable to ask for sample code snippets to be 99% ready to run.

**Comment by shepsii** [comment]
I disagree. Any competent JavaScript developer can figure it out.

Furthermore a quick google shows what this error means and leads you to async functions and working those out.
