### ISSUE TITLE
Calculated expires_at ignores created_at

### ISSUE THREAD

**Issue by 0xR** [lelylan/simple-oauth2#225]
When expires_in is used in the token this library will add the expires_in to the current date. This is incorrect since there might be created_at field as well.

See the code here:
https://github.com/lelylan/simple-oauth2/blob/master/lib/access-token/parse-token.js#L17

**Comment by ziogas** [comment]
Can confirm that the issue/bug still exists. The easy fix though would be to create missing `expires_at` field before passing it to the library.

```js
if (!token.expires_at) {
    token.expires_at = new Date((parseInt(token.created_at, 10) + parseInt(token.expires_in, 10)) * 1000);
}

**Comment by jonathansamines** [comment]
@ziogas Can you create an isolated reproduction example to take a look at this issue? Reading at the code doesn't seem that to be possible because we first verify that expires_at [doesn't exists](https://github.com/lelylan/simple-oauth2/blob/master/lib/access-token/parse-token.js#L11).

**Comment by jonathansamines** [comment]
Closing due inactivity. Feel free to reopen with a reproduction example of the problem if you are still experiencing this issue.

**Comment by praWeb** [comment]
Can say that this is still occuring

**Comment by jonathansamines** [comment]
@praWeb Nothing I can do without a reproduction. Please open other issue with a reproduction example or a failing test to further investigate.
