### ISSUE TITLE
custom client strategies

### ISSUE THREAD

**Issue by cmawhorter** [lelylan/simple-oauth2#230]
i noticed #210 yesterday and didn't care.  today... it's my problem.  ugh.

a few open issues could be solved or worked around if you expose a way of creating custom strategies. 

that would help with #210, #220, #211, possibly #219.

maybe something like this thrown together thing below.

```js
// ... code snip ...

// diff:
// expose core module
const coreModule = require('lib/core');
const defaultEncoding = require('lib/encoding');

module.exports = {
  create(opts = {}) {
    const options = Joi.attempt(opts, optionsSchema, 'Invalid options provided to simple-oauth2');

    return {
      accessToken: accessTokenModule(options),
      ownerPassword: passwordModule(options),
      authorizationCode: authCodeModule(options),
      clientCredentials: clientCredentialsModule(options),
      // diff:
      createCustomStrategy(strategyDefinition, encoding = defaultEncoding) {
        // diff: change coreModule signature to accept encoding
        const strategy = strategyDefinition(options, encoding);
        return strategy;
      }
    };
  },
};
```

also - fwiw - having a factory return everything like this does not play nicely with tree shaking.  

and hapijs/* means i have to make this lib external with rollup because the folks over at hapijs are _different_. i've yet to get joi,etc. to bundle nicely..  /rantend

**Comment by jonathansamines** [comment]
@cmawhorter All issues reported here, will be solved in v3. Please reference each issue to better understand how each particular problem was solved or wait until v3 is release (will make by best to document new features and/or breaking changes)
