### ISSUE TITLE
Question: How to detect expiration of refresh token

### ISSUE THREAD

**Issue by jimmykane** [lelylan/simple-oauth2#233]
Hi, 

this is more of a question that I did not find documented. 

I know we can refresh an access token via detecting the expiry but does the same method apply for the refresh token or is there something else needed?

**Comment by jonathansamines** [comment]
@jimmykane That pretty much depends on the oauth2 implementation. Usually, for most of grants, refreshing an oauth2 refresh token should work just as a normal access token, but note that client_credentials, usually does not support refresh tokens at all.

**Comment by jonathansamines** [comment]
@jimmykane That pretty much depends on the oauth2 implementation. Usually, for most of grants, refreshing an oauth2 refresh token should work just as a normal access token, but note that client_credentials, usually does not support refresh tokens at all.

**Comment by jimmykane** [comment]
@jonathansamines  Thanks . I figured that out in the end. Thanks again !
