### ISSUE TITLE
Receiving 400 from dropbox when upgfarding 1.6.0->2.x.x (2.4.0)

### ISSUE THREAD

**Issue by ed4becky** [lelylan/simple-oauth2#247]
I am trying to upgrade to the latest version of this package. I am finding an issue when calling simpleOAuth2.authorizationCode.getToken()
I consistently get a 400 from dropbox. I use the same code between 1.6.0 and 2.x.x:

> this.simpleOAuth2.authorizationCode.getToken({
>           grant_type: 'authorization_code',
>           code: authCode,
>           client_id: this.CLIENT_ID,
>           client_secret: this.CLIENT_SECRET,
>           redirect_uri: 'http://localhost:3031/callback'
>         }, (error, result) => {<my code>});

I have tried to debug myself to now avail.

A little more context:

>     const httpServer = app.listen(3031);
>     const authorizationUri = this.simpleOAuth2.authorizationCode.authorizeURL({
>       redirect_uri: 'http://localhost:3031/callback',
>       state: state
>     });
> 
>     const promise = new Promise<any>((resolve, reject) => {
>       app.get('/callback', (req, res) => {
>         const authCode = req.query.code;
>         this.logger.info('Code: ' + authCode);
>         this.simpleOAuth2.authorizationCode.getToken({
>           grant_type: 'authorization_code',
>           code: authCode,
>           client_id: this.CLIENT_ID,
>           client_secret: this.CLIENT_SECRET,
>           redirect_uri: 'http://localhost:3031/callback'
>         }, (error, result) => {<my code>});
>
>       child_process.execSync('open -a \'/Applications/Google\ Chrome.app\' \'' + authorizationUri + '\'');
>

**Comment by jonathansamines** [comment]
Hi @ed4becky I am not quite certain of what specifically caused the issue. However I found out a couple of things about this particular provider:

- It requires you to send the credentials over POST with form encoding or through basic header authentication. This library supports the former.

- The token host is different than the authorization host (https://dropbox.com vs https://api.dropbox.com). This library has support to specify both as separate options for such scenarios

- For some weird reason, it required me to also resend the redirect_uri during the token exchange even though [their documentation](https://www.dropbox.com/developers/documentation/http/documentation) state it is an optional parameter. You can also provide this information through options by using the `authorizationCode.getToken` method.

I have also put together an example which is working for me at #249 . Please take a look at it, and let me know if that works for you.

**Comment by jonathansamines** [comment]
@ed4becky Will close this issue for now. Feel free to reopen if the example above didn't help out.

**Comment by ed4becky** [comment]
This worked great, thanks for the example.
