### ISSUE TITLE
http_proxy, https_proxy, and no_proxy environment variables doesn't impact on the request

### ISSUE THREAD

**Issue by shkedi** [lelylan/simple-oauth2#251]
On a previous simple-auth2's version (for example 1.4.0), the environment variables: http_proxy, https_proxy, and no_proxy were impacted on the request and pass the request via the proxy. In a newer version (at least above 2.2.1) the variables don't impact on the request and the request doesn't pass through the proxy. 

my app was written on Node, version 10.16.0. run inside a docker container and try to get a SalesForce's token through the proxy

**Comment by shkedi** [comment]
I am looking in the changelog. Probably it started to appear on version 2.0.0, when the internal request library to wreck
https://github.com/lelylan/simple-oauth2/blob/master/CHANGELOG.md

**Comment by shkedi** [comment]
Maybe it can help:
https://github.com/hapijs/wreck/issues/64

**Comment by jonathansamines** [comment]
@shkedi Yes, you are right. The new internal library doesn't support that. However it does support the `agent` option which allows you to create this functionality.

**Comment by shkedi** [comment]
Thanks @jonathansamines.
I saw this thread https://github.com/lelylan/simple-oauth2/issues/16
and tried this code:
```
const HttpsProxyAgent = require('https-proxy-agent');
let oauth = OAuth2.create({
 client: {
 },
 auth: {
 },
 http: {
   agent: new HttpsProxyAgent('http://<proxy-url>:<proxy-port>'),
 },
});
```
but I am getting this error:
_"options.agent" property must be one of type Agent-like Object._

**Comment by jonathansamines** [comment]
Hi @shkedi Sorry for the late response. I tried the exact same example you provided and was able to get it working without issue. Are you still experiencing the problem? Otherwise, can you provide a reproduction example to take a look at?

**Comment by jonathansamines** [comment]
Feel free to reopen with additional details (ideally, a reproduction) if you are still experiencing this issue.
