### ISSUE TITLE
Does this library rely on the legacy ~/resources audience?

### ISSUE THREAD

**Issue by VictorioBerra** [lelylan/simple-oauth2#258]
https://github.com/IdentityServer/IdentityServer4/releases/tag/3.0.0

> We removed the old legacy ~/resources audience from access tokens and use a typ header instead. This might cause problems with some legacy JWT validation libraries and needs some testing.

I am wondering because I do not want to break compatibility with users that are using simple-oauth2 with my identity server.

**Comment by jonathansamines** [comment]
@VictorioBerra Sorry, but I definitely have no idea of what are you asking for. Can you elaborate?

**Comment by VictorioBerra** [comment]
Does this library do any validating of tokens? Or does it only request them? There might be no need for concern here.

**Comment by jonathansamines** [comment]
@VictorioBerra This library just handles the token retrieval process.
