### ISSUE TITLE
wreck is depreciated

### ISSUE THREAD

**Issue by lukepighetti** [lelylan/simple-oauth2#261]
https://www.npmjs.com/package/wreck

**Comment by jonathansamines** [comment]
@lukepighetti Yes and because of breaking changes on v15 (@hapi/wreck) I am planning to update this particular dependency on a major version.

**Comment by paulmarshall** [comment]
Timescale?

**Comment by jonathansamines** [comment]
@paulmarshall Probably by the end of the month.

**Comment by jonathansamines** [comment]
Solved by #260
