### ISSUE TITLE
Support for JWT as Authorization Grant

### ISSUE THREAD

**Issue by jyotirmoypan** [lelylan/simple-oauth2#264]
I am planning to use the library as it is very easy to integrate and well documented. However, there is a chance I may use JWT as authorization grant in future. What options would I have in that case? If I need to switch the npm library then, I would have to go with another library in that case.

**Comment by jonathansamines** [comment]
Sorry, I have no experience nor use frequently the JWT authorization grant. Will gladly accept a PR, but won't be adding that functionality myself.
