### ISSUE TITLE
Url.URL is not a constructor

### ISSUE THREAD

**Issue by paulmarshall** [lelylan/simple-oauth2#265]
Running node `10.16.3` and I get this error using simple-oauth2 version `2.5.1` in this call:

`authorizationCode.getToken(tokenConfig)`

This is the line of code is blowing on:

> internals.Client.prototype._request = function (method, url, options, relay, _trace) {
>   const uri = {};
>   let parsedUri;
> 
>   if (options.socketPath) {
>     uri.socketPath = options.socketPath;
>     delete options.socketPath;
>     parsedUri = Url.parse(url);
>   } else {
>     uri.setHost = false;
>     **parsedUri = new Url.URL(url);**
>   }

**Comment by jonathansamines** [comment]
@paulmarshall I just tried all library integration tests in that specific version node, and didn't get any error. Can you confirm your Node.js version is indeed `10.16.3`?

See: https://travis-ci.org/lelylan/simple-oauth2/jobs/593029079

**Comment by jonathansamines** [comment]
Feel free to reopen if the issue persist.

**Comment by mmutas** [comment]
I got the same problem. The package "wreck" is deprecated, and available at "@hapi/wreck". The source code provided in the first message is from the package "wreck".

**Comment by jonathansamines** [comment]
@mmutas as previously mentioned, unless a reproduction is provided there is no much I can do.

**Comment by paulmarshall** [comment]
In term of reproducing this, it’s always difficult to give details because invariably their is a need to add a third party lib half way through a project - a project that will contain lots of code, configuration, hosting complexities blah blah.

Wen I ran “node -v”, I got 10.6.3. I’m running Windows, Visual Code etc.

So this is clearly using Node 6+ so URL would be part of the code Node SDK, therefore URL.Url would never work.

**Comment by grigorkin** [comment]
The same problem.

[https://www.dropbox.com/s/np0x1wuig6c4q78/%D0%A1%D0%BA%D1%80%D0%B8%D0%BD%D1%88%D0%BE%D1%82%202019-11-14%2008.49.18.png?dl=0](https://www.dropbox.com/s/np0x1wuig6c4q78/%D0%A1%D0%BA%D1%80%D0%B8%D0%BD%D1%88%D0%BE%D1%82%202019-11-14%2008.49.18.png?dl=0)

```
$node
> process.version
'v12.12.0'
```

**Comment by jonathansamines** [comment]
@grigorkin How are you providing the "url" module to the browser? Perhaps the mechanism used there is not providing a [suitable public API](https://nodejs.org/docs/latest-v10.x/api/url.html#url_class_url) for that module?

**Comment by paul121** [comment]
I've just come across this same issue too. Trying to use `simple-oauth2` with webpack. At first I thought `@hapi/wreck` was using the legacy Node `url` method, but I'm not sure if this is the case. I think it is related to what @jonathansamines mentioned. 

What's interesting... only the docs for [v8.x](https://nodejs.org/docs/latest-v8.x/api/url.html#url_url_strings_and_url_objects) mention the following:
> Note: In Web Browsers, the WHATWG URL class is a global that is always available. In Node.js, however, the URL class must be accessed via require('url').URL

After reading that, I tried changing `Url.URL` to `URL` on L100, L113, and L561 (https://github.com/hapijs/wreck/blob/master/lib/index.js#L100) - **this works in the browser!**

I don't know all the implications for refactoring `Url.URL` to `URL`, but it might be worth looking into?

<hr>
Relevant docs:

 - https://nodejs.org/docs/latest-v10.x/api/url.html#url_url
 - legacy object is created by `url.parse()` - https://nodejs.org/docs/latest-v10.x/api/url.html#url_legacy_url_api

Relevant issue and pr:
 - https://github.com/hapijs/wreck/issues/238
 - https://github.com/hapijs/wreck/pull/242

**Comment by jonathansamines** [comment]
@paul121 The global `URL` seems to be only available in Node 10 and newer versions. Since we still support Node 8, we can change this module to use the global, but would have to be done in a new major version. I do have plans to release a new version with some additional breaking changes. Mind creating a pull request to the develop branch with those changes?

**Comment by paul121** [comment]
@jonathansamines I've just realized this issue thread was specific to the `authorizationCode.getToken()` method. I'm only using the `ownerPassword.getToken()` method right now - but seeing the same error rise from the `@hapi/wreck` dependency. 

Correct me if I'm wrong, but I don't think a PR to this repo could fix the issue I'm seeing? Unless we can override the behavior of the hapi client?

Happy to submit a PR if it would help!

**Comment by jonathansamines** [comment]
@paul121 you are right, there is nothing we can do, unless `@hapi/wreck` is also updated by itself. I would still accept a PR to solve the issue for the one method this library controls: [.authorizeURL](https://github.com/lelylan/simple-oauth2/blob/master/lib/grants/authorization-code.js#L23)
