### ISSUE TITLE
UTF-8 encode user-pass using `encodeURI` method instead of `encodeURIComponent`

### ISSUE THREAD

**Issue by anselm94** [lelylan/simple-oauth2#271]
As per [RFC 7617](https://tools.ietf.org/html/rfc7617), many modern implementation encode `user-pass` in UTF-8. According to [MDN Web docs `encodeURI()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURI) documentation, there is difference between `encodeURI` and `encodeURIComponent` which does UTF-8 encoding

https://github.com/lelylan/simple-oauth2/blob/fe40ad5df57694683cb11f9add644a00f88b4722/lib/encoding.js#L7

Here, instead of replacing characters (like `+`, in this case), `encodeURI` can be used, as the characters `;,/?:@&=+$#` will be escaped by default.

#### Reason for this issue

`clientid`, `clientsecret` generally tend to have special characters which are generally unescaped for UTF encoding, but encoded by URI component encoding, throwing 404 when used for Client Credentials way for oAuth2

**Comment by librarywebchic** [comment]
I'm using the latest release and I'm seeing this issue too. When creating a Basic Authentication header still. Special characters in the client id and secret are being url encoded before things are base64encoded. This makes Basic Authentication fail in all the patterns
