### ISSUE TITLE
Oauth error: Error: Invalid defaults value: must be an object

### ISSUE THREAD

**Issue by suculent** [lelylan/simple-oauth2#274]
After upgrading from 2.5.2 to 3.0.1 I'm receiving the `Oauth error: Error: Invalid defaults value: must be an object`. Any changes to configuration requirements since then?

```
const soauth = require('simple-oauth2');
var oauth2;

const credentials = {
      client: {
        id: <client_id>,
        secret: <client_secret>,
      },
      auth: {
        tokenHost: 'https://accounts.google.com/',
        authorizePath: '/o/oauth2/auth',
        tokenPath: '/o/oauth2/token'
      }
    };
    try {
      oauth2 = soauth.create(credentials);
    } catch(error) {
      console.log(error);
    }
```

**Comment by jonathansamines** [comment]
Hi @suculent I just tried your exact example with simple-oauth2@3.0.1 and got no errors. 

See: https://runkit.com/jonathansamines/simple-oauth2-v3configuration/branches/master

If you can create an isolated reproduction example, that would help to trace the problem.

**Comment by jonathansamines** [comment]
Feel free to reopen with a reproduction example if you are still experiencing this issue.

**Comment by suculent** [comment]
Well, it does not fail that early. It returns `Error: Invalid defaults value: must be an object` in app's `/oauth/cb` GET endpoint which calls `oauth2.authorizationCode.getToken()`.

**Comment by krvajal** [comment]
I have the same issue
