### ISSUE TITLE
URL encoding Authorization header causing issues

### ISSUE THREAD

**Issue by bilts** [lelylan/simple-oauth2#276]
The library had been working great for me until 3.0.1.  It's now causing problems authentication.  I've tracked this down to the fact that it's now URL encoding the authorization header components before base64 encoding them.  This doesn't seem to be part of the HTTP spec and essentially is causing me to send the wrong password to the server.

**Comment by blangero** [comment]
Same issue! 
for me it's encoding.js -> line 25: const encodedCredentials = `${useFormURLEncode(clientID)}:${useFormURLEncode(clientSecret)}`; 
caused wrong Authorization.

**Comment by jaggygit** [comment]
For me it's encoding.js too. I have client secret with special characters. if I remove `useFormURLEncode` it works and I get the token.

**Comment by vslepkan** [comment]
I have the same problem as above.

**Comment by OrangeDog** [comment]
> This doesn't seem to be part of the HTTP spec

But it is part of the [OAuth2 spec](https://tools.ietf.org/html/rfc6749#section-2.3.1).

**Comment by jonathansamines** [comment]
Hi @vslepkan @jaggygit @bilts @blangero 

Given the number of issues reported, I just added a configuration option to setup how header credentials are encoded. From [simple-oauth2@3.3.0](https://github.com/lelylan/simple-oauth2/blob/master/CHANGELOG.md#330) you can use the `options.credentialsEncodingMode=loose`(no encoding) to opt-out of the default **strict** behavior (form encoding).

Please look at the [module documentation](https://github.com/lelylan/simple-oauth2/blob/master/API.md) and let me know if that works for everyone.
