### ISSUE TITLE
Access Token Error Converting circular structure to JSON

### ISSUE THREAD

**Issue by oz-messapps** [lelylan/simple-oauth2#278]
Hello Lelylan,
Got an Error when const token = oauth2.accessToken.create(result);

**Comment by oz-messapps** [comment]
No issue here, had extra property in a token object,  just needed to folow to right structure).

**Comment by nike171196** [comment]
Hello @oz-messapps,

i have got the same problem and can not figure out what i am doing wrong. Could you please tell me what was the extra property you had to remove. Maybe it solves my problem too.

**Comment by oz-messapps** [comment]
Hello @nike171196,

Thank you for your question, the answer is obvious, just check the structure of response it should be exact as require in this package)) In my case I had an extra property of the object  here is my example:
const result =
{
     "access_token":"5c2708431f7d",
     "refresh_token":"505ce33e99a6",
     "token_type":"bearer",
     "expires_in":259199
 };
as you can see it has a "token_type" properties, so we had to make this structure match for 
accessToken.create(result);

The simpliest way just destuct this result -> 

const {token_type, result} ={
     "access_token":"5c2708431f7d",
     "refresh_token":"505ce33e99a6",
     "token_type":"bearer",
     "expires_in":259199
 };

we will get right result stucture and accessToken.create(result) without any errors;

Hope it will help you!))

Cheers,
OZ
