### ISSUE TITLE
refresh() throws "The content-type is not JSON compatible"

### ISSUE THREAD

**Issue by korneliuscode** [lelylan/simple-oauth2#279]
I'm using simple-oauth2 for Microsoft Graph requests (basically using [this example](https://docs.microsoft.com/en-us/graph/tutorials/node)). This works well so far. But when I want to refresh my access token `var newToken = await storedToken.refresh();`, I get an error 

> The content-type is not JSON compatible

This is thrown in `wreck`'s `index.js` and it seems like there is no `content-type` set in the headers, while the `mode` is set to `strict`. The problem is, that I have no idea how to change this or why this is happening. It only happes on `refresh()`.

**Comment by jonathansamines** [comment]
@korneliuscode You can use the `options.http` options  to set any wreck option when constructing an instance of this library.

**Comment by korneliuscode** [comment]
It was an issue with the examples proposed configuration. This was the suggested config:
```
OAUTH_AUTHORITY=https://login.microsoftonline.com/common
OAUTH_ID_METADATA=/v2.0/.well-known/openid-configuration
OAUTH_AUTHORIZE_ENDPOINT=/oauth2/v2.0/authorize
OAUTH_TOKEN_ENDPOINT=/oauth2/v2.0/token
```
wreck uses [Url.URL][1] to combine `OAUTH_AUTHORITY` with `OAUTH_TOKEN_ENDPOINT` which results in `https://login.microsoftonline.com/oauth2/v2.0/token` and therefore loses `common`. This results in a `404`.

I changed the config slightly and removed the leading slashes from the relative paths and added a trailing slash to the base URL.
```
OAUTH_AUTHORITY=https://login.microsoftonline.com/common/
OAUTH_ID_METADATA=/v2.0/.well-known/openid-configuration
OAUTH_AUTHORIZE_ENDPOINT=oauth2/v2.0/authorize
OAUTH_TOKEN_ENDPOINT=oauth2/v2.0/token
```
So that `OAUTH_TOKEN_ENDPOINT` is relative. I have not figured why it worked for authorize though, but still works.

  [1]: https://nodejs.org/api/url.html#url_constructor_new_url_input_base

**Comment by Nico-L** [comment]
Hello,

I have the same problem with an access to a nextcloud instance. I didn't find the http option in the wreck package. The thing is that I have to debug my app as I don't know the answer of Nextcloud or even if Nextloud is correctly setup.

Which would be the best way to debug and see the return of the server?

thanks

**Comment by jonathansamines** [comment]
@Nico-L You can find the `options.http` configuration on this library documentation. We make sure properly pass any configuration option under that key to the *wreck* package. Regarding of how to debug this library you may find `DEBUG=*simple-oauth2*` environment variable useful.

**Comment by jonathansamines** [comment]
Feel free to reopen if you are still experiencing issues with this library.

**Comment by LakmalHarshana** [comment]
set the auth property in this way

`auth: {
tokenHost: 'https://login.microsoftonline.com/common/',
tokenPath: 'oauth2/v2.0/token',
authorizePath: 'oauth2/v2.0/authorize',
},`
