### ISSUE TITLE
subdomains

### ISSUE THREAD

**Issue by eldi007** [lelylan/simple-oauth2#29]
I set up the authorization for the vk.com, where
, authorizationUri = 'oauth.vk.com/authorize'
, tokenGetUri = 'api.vk.com/oauth/token'

`site` I had to do 'https: //', as an empty` site` get an error in this test
./lib/core.js
....
36   if (!config.clientID || !config.clientSecret || !config.site)

**Comment by jonathansamines** [comment]
Closed by #75
