### ISSUE TITLE
TokenHost is ignored in request

### ISSUE THREAD

**Issue by adtype-com** [lelylan/simple-oauth2#305]
I'm trying to set up the Facebook OAuth flow to get an access token and am encountering a problem with the `tokenHost` and `tokenPath` parameters. When using the configuration below, I receive 404 errors. 

```javascript
   this.credentials = {
      client: {
        id: '123',
        secret: '1234567890',
        idParamName: 'app_id'
      },
      auth: {
        tokenHost: 'https://graph.facebook.com/oauth',
        tokenPath: '/access_token',
        authorizeHost: 'https://www.facebook.com/dialog/',
        authorizePath: './oauth'
      }
    }
    this.oauth = oauth2.create(this.credentials)
```

### Response

```
Response Error: 404 Not Found
    Error: Response Error: 404 Not Found
        at internals.Client._shortcut (XXXX/node_modules/@hapi/wreck/lib/index.js:643:11)
        at process._tickCallback (internal/process/next_tick.js:68:7)
```

Debugging the code I found that it was attempting make a request to `/access_token` without appending the `tokenHost` variable to the URL of the request. Note how only the `tokenPath` is used in the following line of code.

https://github.com/lelylan/simple-oauth2/blob/8e689a9db84986b1ab94c2e9cd5921835b814dc7/lib/grants/client-credentials.js#L22

The only way I managed to get it to work was to include the full URL within the `tokenPath` option as follows:

```javascript
   this.credentials = {
      auth: {
        tokenHost: 'https://graph.facebook.com/oauth',
        tokenPath: 'https://graph.facebook.com/oauth/access_token'
      }
}
```

Is this expected behaviour? Thanks in advance.

**Comment by jonathansamines** [comment]
You might one to try with the following configuration:

```js
{
      client: {
        id: '123',
        secret: '1234567890',
        idParamName: 'app_id'
      },
      auth: {
        tokenHost: 'https://graph.facebook.com',
        tokenPath: '/oauth/access_token',
        authorizeHost: 'https://www.facebook.com',
        authorizePath: '/dialog/oauth'
      }
    }
```

The issue might be related to how URL are resolved by the global URL module. Please let me know if that works for you.

**Comment by jonathansamines** [comment]
Feel free to re-open if the above solution doesn't works.
