### ISSUE TITLE
Accept url parameters on getToken?

### ISSUE THREAD

**Issue by AppElent** [lelylan/simple-oauth2#315]
Hi, I want to get the code for an accounts which expects the information in the url. Documentation says this:

![image](https://user-images.githubusercontent.com/26725094/80210544-3abb5b80-8634-11ea-9fc8-360d4a652418.png)

It appears you are sending the credentials as header or body.

Can someone help me?

**Comment by jonathansamines** [comment]
@AppElent Credentials as body should work for you. If that is not the case, please create an isolated reproduction to take a look at.

**Comment by jimmykane** [comment]
Hi how to use this ?
