### ISSUE TITLE
Refresh Token without Authorization header

### ISSUE THREAD

**Issue by gsferreira** [lelylan/simple-oauth2#32]
Hi!

I'm consuming an oAuth2 Provider (built with [DotNetOpenAuth](https://github.com/DotNetOpenAuth/DotNetOpenAuth)) that doesn't accept the Authorization header in the refresh token request, but needs it to request a new token. 

There's anyway to overcome this?

I have changed the following validation, in the core.js and it works fine.

```else if (config.useBasicAuthorizationHeader && config.clientID && !params.client_id)```
by
```else if (config.useBasicAuthorizationHeader && config.clientID && !params.client_id && params.grant_type !== 'refresh_token')```

Is this the correct solution?

**Comment by jonathansamines** [comment]
This like a correct solution, but is always applying this exclusion logic, if valid we need to add this as a configurable property and add test to verify this solution. @gsferreira do you have time to work on this?
