### ISSUE TITLE
How to re-create the access token object?

### ISSUE THREAD

**Issue by roychri** [lelylan/simple-oauth2#327]
Hello,

In your documentation for version 4.0.0 it says that you can refresh a token like this:

```
async function run() {
  if (accessToken.expired()) {
    try {
      const refreshParams = {
        scope: '<scope>',
      };

      accessToken = await accessToken.refresh(refreshParams);
    } catch (error) {
      console.log('Error refreshing access token: ', error.message);
    }
  }
}
```

There's no reason to refresh the token you just created, you would do that only for a token that has expired, which could be a while. So one needs to save the access/refresh token somewhere (a secured database for example).
Then when it's time to refresh it, you need to create a new `accessToken` object so you can call `refresh()` on it.

But I cannot see how I can do that with your public API.

So my question is, if I have the token's access and refresh, pulled from a database, how do I refresh it?

The only way I found was to do this:

```
const AccessToken  = require( 'simple-oauth2/lib/access-token' );
const OAuthConfig  = require( 'simple-oauth2/lib/config' );
const OAuthClient  = require( 'simple-oauth2/lib/client' );
function run( credentials, tokenFromDb ) {
    const config = OAuthConfig.apply( credentials );
    const client = new OAuthClient( config );
    const tokenObject = {
        access_token: tokenFromDb.access_token,
        refresh_token: tokenFromDb.refresh_token
    };
    const accessToken = new AccessToken(
        config, client,
        tokenObject
    );

    return accessToken.refresh()
}
```

Is that the recommended approach?

Thanks.

**Comment by jonathansamines** [comment]
Hi @roychri I completely overlooked/forgot how you would usually refresh an access token. I added support to serialize/parse access tokens again at #328 which was published in 4.1.0. Can you give it a try and let me know if that works?

**Comment by jonathansamines** [comment]
Feel free to reopen if still experiencing issues while re-creating access tokens.

**Comment by wallzero** [comment]
I think I am looking for something similar. Many folks using OAuth are doing so with stateless services. Only the user has the tokens. The access token and user credentials are not needed to obtain new access and refresh tokens - so long as you have the previous unexpired refresh token.

I used @roychri's example above and it works well. It'd be nice if it was wrapped in a convenient function or something. This library should be able to request a new access and refresh token given:
* The auth server url and credentials (ModuleOptions)
* The previous refresh unexpired token
