### ISSUE TITLE
Provide typing

### ISSUE THREAD

**Issue by Sytten** [lelylan/simple-oauth2#334]
## Context

* *node version*: All
* *module version*: >2.5.0
* *environment*: All

#### What problem are you trying to solve?

The only typing available for this library in `@types/simple-oauth2` is very old and is not corresponding with the latest version of the library. This basically makes the library unusable with Typescript. Would it possible to provide typing?

Thanks!

**Comment by jonathansamines** [comment]
@Sytten Yes, not against it, but since I don't use typescript myself I don't have the necessary knowledge to put that in place. I am open to PR that can guarantee that:

- Providing typings work for the current major library version
- Provide a way to ensure we don't break those types as we make changes to the library

**Comment by Sytten** [comment]
Verify the typing could be done with https://github.com/SamVerschueren/tsd or https://github.com/microsoft/dtslint

**Comment by Zageron** [comment]
`npm i simple-oauth2@2.5.2` is a poor solution, but worked for me in the meantime. The examples in the https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/simple-oauth2/simple-oauth2-tests.ts file helped me do what I needed.

**Comment by nazarkulyk** [comment]
Typings are not compatible to changes with current version starting with 4.0.0. Last compatible version ist @types/simple-oauth2 = 2.5.3 with simple-oauth2 = 3.4.0

**Comment by namdien177** [comment]
Having an official Typing support will be great as TypeScript is more and more popular.
And because of mismatching version of `@types/simple-oauth2` and `simple-oauth2`, I lost the entire day to debug and fix.

And since I tired of waiting, I made a simple typing file for this library (based on the original `@types/simple-oauth2`). Feel free to use and comment as this is the first time I do this typing thing.

https://gist.github.com/namdien177/064db5d07850ab28714b6e41858a7e0c

**Comment by Sytten** [comment]
@namdien177 I suggest you make a PR on the @types package. That would really benefit the community.

**Comment by namdien177** [comment]
Honestly, I want to do that but I don't have any experience with creating PR in the community repo; also, I still need to check and tweak my typing version for a few days to ensure it will work.
I will try to make a PR when everything is good to go.

**Comment by jimmykane** [comment]
In regards to this, when upgrading to 4.x I get in my firebase project  

```
  at Object.<anonymous> (/Users/dimtrioskanellopoulos/Projects/track-tools/functions/node_modules/simple-oauth2/index.js:3:16)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
⚠  We were unable to load your functions code. (see above)
   - It appears your code is written in Typescript, which must be compiled before emulation.
   - You may be able to run "npm run build" in your functions directory to resolve this.

```

I suppose it's related. 

Any tip. ?

**Comment by jimmykane** [comment]
@namdien177 how can one load/refer to your typing file ?

**Comment by namdien177** [comment]
> @namdien177 how can one load/refer to your typing file ?

I believe you can follow [these steps](https://stackoverflow.com/questions/38971984/how-to-add-custom-typings-in-typescript-2-0-3-0) or [these](https://www.detroitlabs.com/blog/2018/02/28/adding-custom-type-definitions-to-a-third-party-library/)?

For my current project, I just replace the content of @types/simple-oauth2 with mine.

**Comment by jonathansamines** [comment]
@jimmykane Please also note that we do rely on some Node 12 only features on v4. Please your environment supports that.

**Comment by Zageron** [comment]
Oooh, thank you @namdien177 ! :D

**Comment by jimmykane** [comment]
@jonathansamines  ok thank you very much. This is useful since Firebase has 10. 

I ll hold back a bit and thanks again

**Comment by ziv** [comment]
https://github.com/lelylan/simple-oauth2/pull/342

**Comment by namdien177** [comment]
![image](https://user-images.githubusercontent.com/29449869/88000913-04a15100-cb29-11ea-933e-81014542ca54.png)
It's on guys.

**Comment by jonathansamines** [comment]
That's good news @namdien177. Since the issue seem to be solved now, will close this issue.
