### ISSUE TITLE
Support query params in tokenPath & AuthorizePath

### ISSUE THREAD

**Issue by tanjacky** [lelylan/simple-oauth2#335]
#### Context

* *node version*: 12.16.3
* *module version with issue*: 4.1.0
* *last module version without issue*: n/a
* *environment* (e.g. node, browser, native): node
* *any other relevant information*:

#### What are you trying to achieve or the steps to reproduce?

Trying to integrate with Microsoft Dynamics 365 Business Central. Their [documentation](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-develop-connect-apps#exploring-the-apis-with-postman-and-aad-authentication) suggests we use:
```js
    auth: {
      tokenHost: 'https://login.windows.net/',
      tokenPath: `${process.env.TENANT_DOMAIN}/oauth2/token?resource=https://api.businesscentral.dynamics.com`,
      authorizeHost: 'https://login.windows.net/',
      authorizePath: `${process.env.TENANT_DOMAIN}/oauth2/authorize?resource=https://api.businesscentral.dynamics.com`,
    }
```

#### What was the result you got?
The authorization URL returned looks like:
```
https://login.windows.net/<retracted>/oauth2/authorize?resource=https://api.businesscentral.dynamics.com?response_type=code&client_id=<retracted>&redirect_uri=<retracted>
```
Notice there are two `?` in the URL

#### What result did you expect?
I expect the authorization URL to be:
```
https://login.windows.net/<retracted>/oauth2/authorize?resource=https://api.businesscentral.dynamics.com&response_type=code&client_id=<retracted>&redirect_uri=<retracted>
```

**Comment by jonathansamines** [comment]
@tanjacky Please take a look at #324. I have a solution to the problem in #332, but will require a major version bump in it's current form.

**Comment by tanjacky** [comment]
@jonathansamines Thanks for that, did not realize an issue was already created. 

> Query params on the token path should work, please confirm if they don't.

Yes, it does work. There was a bug in my code which led me to believe it did not.
You can close this and I will keep an eye out for `v5`.
Thanks!
