### ISSUE TITLE
Authorization Code->Get token adds Authorization header which doesn't work with Mailchimp

### ISSUE THREAD

**Issue by edtownend** [lelylan/simple-oauth2#343]
#### Context

* *node version*: 13.7.0
* *module version*: 4.1.0
* *environment* (e.g. node, browser, native): node
* *any other relevant information*: Connecting to the Mailchimp API - https://mailchimp.com/developer/guides/access-user-data-with-oauth-2

#### How can we help?

Hi, thanks for a great library. I'm currently using it to connect to Mailchimp's API using the Authorization Code flow (https://mailchimp.com/developer/guides/access-user-data-with-oauth-2) and running into the same issue referenced here https://github.com/lelylan/simple-oauth2/issues/197.

Digging deeper I've found the problem is that the library is adding a `Authorization: Basic xxxxxx` header to the get token request, which causes Mailchimp to return a 400 error. I can't see however where this header is being added, or where it's getting the key it uses. As far as I understand, the Authorization header is unnecessary when getting the initial token from an authorization code? As per the docs it's not possible to remove this header by passing an empty headers object as the second param to AuthorizationCode.getToken.

Thanks!

**Comment by jonathansamines** [comment]
@edtownend Please look at the [options.authorizationMethod](https://github.com/lelylan/simple-oauth2/blob/master/API.md#options) option. You may want to change it from `header` to `body`. Haven't tried it yet though. Please provide an isolated example to take a look at if the issue persist.
