### ISSUE TITLE
Accept arbitrary headers

### ISSUE THREAD

**Issue by findlay-hannam** [lelylan/simple-oauth2#344]
#### Context

* *node version*: 12.18.3
* *module version*: 4.1.0
* *environment* (e.g. node, browser, native): Node server
* *any other relevant information*: None

#### What problem are you trying to solve?

The oauth2 provider I'm trying to use requires a custom header. This library only supports the `Authorization` and `Content-Type` headers, so I can't use simple-oauth2 to authenticate with it.

It would be good to be able to pass arbitrary header values under `config.http.headers`.

#### Do you have a new or modified API suggestion to solve the problem?

```js
const config = {
  client: {
    id: '<client-id>',
    secret: '<client-secret>'
  },
  auth: {
    tokenHost: 'https://api.oauth.com'
  },
  http: {
    headers: {
      'X-Product': 'value-server-requires'
    }
  }
};
```

**Comment by jonathansamines** [comment]
@findlay-hannam You should be able to pass arbitrary headers as specified by your example. See [this test](https://github.com/lelylan/simple-oauth2/blob/master/test/client-credentials-grant-type.js#L211) as a reference. If that's not working for your, please provide an isolated reproducible example to take a look at.
