### ISSUE TITLE
How to pass get query params to a getTokenExchange

### ISSUE THREAD

**Issue by jimmykane** [lelylan/simple-oauth2#346]
#### Context

* *node version*: 12
* *module version*: 4
* *environment* (e.g. node, browser, native): node
* *any other relevant information*: 

#### How can we help?

Hi, 

related to #315 

The requirement is: 

<img width="669" alt="Screenshot 2020-08-28 at 20 11 56" src="https://user-images.githubusercontent.com/1268723/91602063-fab20f80-e96a-11ea-98f9-9df2172e7507.png">

Typically the library works great :-D 

But I cannot figure out how to pass the get params 

Here is what I have tried: 

```


 const serviceConfig = getServiceConfig(serviceName, useStaging)
  let results: AccessToken
  results = await serviceConfig.oauth2Client.getToken(<AuthorizationTokenConfig>{
    code: code,
    scope: serviceConfig.oAuthScopes,
    // state: state,
    client_id: functions.config().corosapi.client_id,
    client_secret: functions.config().corosapi.client_secret,
    redirect_uri: redirectUri
  });

```

**Comment by jimmykane** [comment]
I figured out that using ClientCredentials solves this. Sorry....

**Comment by jimmykane** [comment]
Nope , any advice is welcome. 


Also for 


<img width="638" alt="Screenshot 2020-08-28 at 21 54 16" src="https://user-images.githubusercontent.com/1268723/91610183-0c9aaf00-e979-11ea-96ba-a778be9cddb9.png">

**Comment by jonathansamines** [comment]
@jimmykane You are probably looking for [options.authorizationMethod](https://github.com/lelylan/simple-oauth2/blob/master/API.md#options). Please try changing that option to `body`. If that doesn't work, I would need an isolated reproduction to take a look at.
