### ISSUE TITLE
Support for Self Signed Certificates

### ISSUE THREAD

**Issue by jagradang** [lelylan/simple-oauth2#348]
This was discussed before but was just closed with a global NODE_TLS_REJECT_UNAUTHORIZED value but this isn't really a viable solution for me.

Has this issue since been fixed as the previous issue was raised 3 years ago.  Support should now have been added for self signed certificates?

I get the following error when trying to connect to my app:
 Client request error: self signed certificate in certificate chain

**Comment by jonathansamines** [comment]
You need to provide a valid certificate, or use the described workaround (NODE_TLS_REJECT_UNAUTHORIZED). If that doesn't work for your, please describe the exact solution you are looking for.

**Comment by jagradang** [comment]
Could you provide a link to the template required so I can raise a new issue please.

If we are able to use a valid certificate for the simple oauth2 library that's fantastic and solves my problem.  However the documentation doesn't state anything about how to use a valid certificate hence me raising the issue. If the document can be updated with a section on how to use a valid certificate that will elimate the need for me raising the issue.  If you can confirm that it is possible please that would be really appreciated. (even if you can just pm me a link on how to tldo it will be enough).

Thank you

**Comment by Morl99** [comment]
Maybe somebody else will stumble over this, I reverse engineered the solution. It is indeed possible to pass options to the underlying wreck library. The following code will do it:
```
new AuthorizationCode({
  client,
  auth:, 
  http: {
    agents: {
      https: httpsAgent,
      http:  httpAgent,
      httpsAllowUnauthorized: httpsAgent
    }
  }
})
```
The Agents are the regular [https](https://nodejs.org/api/https.html) and [http](https://nodejs.org/api/http.html) Agents.

A ready to use documentation for this use case would probably help fellow users of simple-oauth2 to implement this easier.
