### ISSUE TITLE
Please remove this

### ISSUE THREAD

**Issue by dam0vm3nt** [lelylan/simple-oauth2#349]
https://github.com/lelylan/simple-oauth2/blob/68394d5aa829a6039fea744d6eb6df2605a8f32f/lib/client/client.js#L19

It's breaking deployment of simple-oauth2 in gcloud functions since v. 4.x

**Comment by jonathansamines** [comment]
@dam0vm3nt See the library [requirements](https://github.com/lelylan/simple-oauth2#requirements). If you need to support older runtime versions use v3.x which is still maintained until Node 10 goes out of LTS.

**Comment by mitchjb2008** [comment]
I'm getting the same error and I'm on Node 12.2.

./node_modules/simple-oauth2/lib/client.js
SyntaxError: ###redacted###\node_modules\simple-oauth2\lib\client.js: Support for the experimental syntax 'classPrivateProperties' isn't currently enabled (19:3):

  17 | 
  18 | module.exports = class Client {
> 19 |   #config = null;
     |   ^

**Comment by mitchjb2008** [comment]
Confirmed to still error out on Node 12.19 (latest)

**Comment by jonathansamines** [comment]
@mitchjb2008 Private class fields are no longer experimental in Node 12. Please verify your runtime. Also, I have provided alternatives in case you are still running on an unsupported runtime.
