### ISSUE TITLE
Specifying Proxy Configuration 

### ISSUE THREAD

**Issue by AnandDivakaran** [lelylan/simple-oauth2#351]
I plan on trying out this library on my client node js code to invoke a pubic resource (api) that is protected using OAuth2.0 client credentials flow. Is there a way i can specify proxy configuration details (host & port) given my client application is residing in a corporate network

**Comment by jonathansamines** [comment]
Hi @AnandDivakaran you should be able to use the [http](https://github.com/lelylan/simple-oauth2/blob/master/API.md#options) option and directly provide an http agent to the underlying [http library](https://hapi.dev/module/wreck/api/?v=17.0.0#defaultsoptions)

**Comment by AnandDivakaran** [comment]
Yes, Thanks
