### ISSUE TITLE
"Unexpected token  in JSON at position 0" when running AuthorizationCode.getToken

### ISSUE THREAD

**Issue by kevindcode** [lelylan/simple-oauth2#359]
#### Context

* *node version*: 12
* *module version*: 4.1.0
* *environment* (e.g. node, browser, native): node
* *any other relevant information*: n/a

#### How can we help?

Hello, I'm hitting an error when calling the `AuthorizationCode.getToken` method and the issue points to a line of code in the `@hapi/wreck` module (@hapi/wreck/lib/index.js:631:26):

![Screenshot 2020-12-15 at 22 54 14](https://user-images.githubusercontent.com/34057567/102282445-8bb3f300-3f28-11eb-88f8-04ad2b3fc00e.png)

The full error message is this:

>
     Error: Unexpected token  in JSON at position 0
        at Object.internals.tryParseBuffer (.../node_modules/@hapi/wreck/lib/index.js:631:26)
        at finish (.../node_modules/@hapi/wreck/lib/index.js:389:30)
        at wrapped (.../node_modules/@hapi/hoek/lib/once.js:17:13)
        at module.exports.internals.Recorder.onReaderFinish (.../node_modules/@hapi/wreck/lib/index.js:436:20)
        at Object.onceWrapper (events.js:420:28)
        at module.exports.internals.Recorder.emit (events.js:326:22)
        at module.exports.internals.Recorder.EventEmitter.emit (domain.js:483:12)
        at finishMaybe (_stream_writable.js:639:14)
        at afterWrite (_stream_writable.js:493:3)
        at afterWriteTick (_stream_writable.js:477:10)
        at processTicksAndRejections (internal/process/task_queues.js:83:21)

The `buffer` value looks something like this:
```
{
  "type": "Buffer",
  "data": [
    31,
    139,
    // ... more numbers
  ]
},
```

#### My code

A stripped down version of the code I'm running looks like the below:

```typescript
import { AuthorizationCode, AuthorizationTokenConfig, ModuleOptions, Token } from 'simple-oauth2';

const config = {
  auth: {
    // ... auth definitions
  },
  client: {
    // ... client definitions
  },
};

const client = new AuthorizationCode(config);

const params: AuthorizationTokenConfig = {
  code: '<some-code>',
  redirect_uri: '<some-callback-link>',
};

const accessToken = await this.client.getToken(params); // 👈🏼 I getting the issue at this point
```

#### Question
I don't know what I'm doing wrong as the `params` object I'm passing in is type checked since I've explicitly declared it as  type `AuthorizationTokenConfig` - so I don't believe there's a problem with the properties defined in this object.

Do you have any ideas why I'm bumping into this error?

Thank you!

**Comment by jonathansamines** [comment]
Hi @kevindcode, your OAuth server is returning a non-JSON response. You might want to try [debugging the module](https://github.com/lelylan/simple-oauth2#debugging-the-module) to understand what your server response is, and keep debugging from that point.

**Comment by kevindcode** [comment]
@jonathansamines you're right, I'm getting a 502 response.

I'm trying to retrieve the access token from `Mailchimp` - do you think this is an issue on their side then? 🤔

**Comment by jonathansamines** [comment]
If you are getting a 502 error, maybe you are hitting the wrong endpoint. I would suggest to looking at their docs do determine what the correct tokens endpoint is. Otherwise, please provide a complete isolated reproduction of your problem (runnable example repository) and I might be able to take a look.

**Comment by jonathansamines** [comment]
Feel free to reopen with additional details.

**Comment by kevindcode** [comment]
@jonathansamines 

Sorry for the delay :)

I've created this repo here:
- https://github.com/kevindcode/mc-integration-test

I've added instructions on how to re-create the issue in the [README](https://github.com/kevindcode/mc-integration-test#mc-integration-test) - let me know if you have any questions!

**Comment by jonathansamines** [comment]
Hi @kevindcode. Thanks for the detailed reproduction. See https://github.com/kevindcode/mc-integration-test/pull/1 for the changes you need to get it working. 

As a side note, I would recommend against using async/await with express as it would lead to problems in production because express doesn't support them.

**Comment by kevindcode** [comment]
Thanks so much @jonathansamines!

Just going to put your solution here in case anyone encounters something similar in the future:
```javascript
const options = {
  auth: {
    tokenHost: 'https://login.mailchimp.com',
    tokenPath: '/oauth2/token',
    authorizeHost: 'https://login.mailchimp.com',
    authorizePath: '/oauth2/authorize'
  },
  client: {
    id: MAILCHIMP_CLIENT_ID,
    secret: MAILCHIMP_CLIENT_SECRET,
  },
  options: {
    authorizationMethod: 'body', // 👈🏼  needed to set this to `body`
  },
};
```

Hope you have a great Christmas! :)
