### ISSUE TITLE
how to setup the twitter request_token ?

### ISSUE THREAD

**Issue by annymosse** [lelylan/simple-oauth2#360]
#### Context

* *node version*:12.X
* *module version*:latest
* *environment* node:

#### How can we help?

where can i setup twitter request_token such as  
```js
// ...
function Strategy(options, verify) {
  options = options || {};
  options.requestTokenURL = options.requestTokenURL || 'https://api.twitter.com/oauth/request_token';
  options.accessTokenURL = options.accessTokenURL || 'https://api.twitter.com/oauth/access_token';
  options.userAuthorizationURL = options.userAuthorizationURL || 'https://api.twitter.com/oauth/authenticate';
// ...
```
to fix the following bug:
`There is no request token for this page. This is the special key we need from apps asking to use your Twitter account. Please come back to the site or application that brought you here and try again; it was probably just a mistake.`

**Comment by annymosse** [comment]
@jonathansamines why did you close it ???!!!!

**Comment by jonathansamines** [comment]
Hi @annymosse I believe your issue is not related with this library, as both the code sample and the error message did not make sense for this library. Please correct me if I am wrong, with additional details on how are you trying to use this library by creating an isolated reproduction example.

**Comment by annymosse** [comment]
actually there's no need to recreate a production link since my request is related to the request token option which it exist on Twitter configs , as an example i provided a link to passport lib which there's ability to attach twitter by providing a request_token url option

https://github.com/jaredhanson/passport-twitter/blob/master/lib/strategy.js#L48

By other question form : "how can i config twitter to work well? (which require [request_token](https://developer.twitter.com/en/docs/authentication/guides/log-in-with-twitter) option whenever it doesn't exist in this lib code)"

**Comment by jonathansamines** [comment]
Go it. Short answer is: You can't.

Looks like that endpoint is used to request tokens using OAuth 1.1 which is not supported by this library. you'll need to either use [OAuth 2.0](https://developer.twitter.com/en/docs/authentication/api-reference/token) or use a different library

**Comment by annymosse** [comment]
thank you
