### ISSUE TITLE
Add possibility to omit `tokenHost`

### ISSUE THREAD

**Issue by tomdohnal** [lelylan/simple-oauth2#362]
#### Context
Not related to a specific version / environment

#### What problem are you trying to solve?

I was trying to implement the oauth flow with the Google Oauth provider.

However, I was not able to accomplish that as Google uses a different "base" URL for the `authorizePath` and `tokenPath` path. (It's `https://accounts.google.com/o/oauth2/v2/auth` for the former and `https://oauth2.googleapis.com/token` for the latter)

I tried to omit the `tokenHost` URL and specify the full URL in the `authorizePath` and `tokenPath` properties but as the `tokenHost` is required (and fails even for an empty string) I was not successful.

One possible workaround could be to create two separate clients and specify different token paths for them.

However, this feels like a workaround rather than a solution

#### Do you have a new or modified API suggestion to solve the problem?
The solution is to be able to omit the `tokenHost` property and allow to specify full (absolute) URLs in the `authorizePath` and `tokenPath` properties instead.

**Comment by ervwalter** [comment]
I might be misunderstanding, but there is an `authorizeHost` option that is used with `authorizePath` so that you can have a different base URL than `tokenHost`.

**Comment by jonathansamines** [comment]
Hi @tomdohnal, as @ervwalter mentioned, using separate hosts should work:

```js
const { AuthorizationCode } = require('simple-oauth2');

const client = new AuthorizationCode({
  auth: {
    // token server
    tokenHost: 'https://oauth2.googleapis.com',
    tokenPath: '/token',

    // authorization server
    authorizeHost: 'https://accounts.google.com',
    authorizePath: '/o/oauth2/v2/auth',
  },
});
```

Feel free to re-open with additional details if your issue cannot be solved with the solution above.
