### ISSUE TITLE
@hapi/boom deprecated dependency

### ISSUE THREAD

**Issue by therealgilles** [lelylan/simple-oauth2#363]
#### Context

* *node version*: v15.8.0
* *module version*: v4.2.0
* *environment* (e.g. node, browser, native): node + browser
* *any other relevant information*:

#### How can we help?
Any plans to update the dependency on @hapi/boom, which is now a deprecated package?

**Comment by jonathansamines** [comment]
I don't think @hapi/boom is deprecated. Please note that we don't directly rely on that package.

Are you getting a deprecation warning of some sort when installing this package alone?

**Comment by therealgilles** [comment]
Oh you're right, simple-oauth2 dependencies look fine. Sorry for the false report. Will close.
