### ISSUE TITLE
Using mTLS alongside simple-oauth2

### ISSUE THREAD

**Issue by ruankotovich** [lelylan/simple-oauth2#365]
#### Context

* *node version*: v12.16.3
* *module version*: 4.x.x
* *environment* (e.g. node, browser, native): node

#### How can we help?
I am using **simple-oauth2** as a client, but there's an aditional step on the auth server itself, I need to send a certificate (mTLS flow), is there a way to import a certificate on NodeJS? or a lib which simple-oauth2 uses in background to send the request? 

Thanks ind advange

**Comment by jonathansamines** [comment]
Hi @ruankotovich You are probably look at the `http` [option](https://github.com/lelylan/simple-oauth2/blob/master/API.md#options), which allows you to provide the underlying client ([wreck](https://hapi.dev/module/wreck)) with most of it's documented options
