### ISSUE TITLE
TypeError: URL is not a constructor

### ISSUE THREAD

**Issue by pravMo** [lelylan/simple-oauth2#366]
#### Context

* *node version*: v14.16.0
* *module version*: v4.2.0
* *environment* (e.g. node, browser, native): react, node 
* *any other relevant information*: have a craco.config.js file which contains Babel plugins and presets

#### How can we help?

Below is code in my authHelper.js file in React, the `registerClient` function is being called in a different React component where `onClick` of a signIn button initiates the AuthorizationCode flow, but I can't get past `client.authorizeURL` cause it throws `TypeError: URL is not a constructor`. Also maybe important to note that if I tried this code snippet in Express, everything works fine.

```
const { AuthorizationCode, AccessToken } = require('simple-oauth2');

var config = {
  client: {
    id: clientId,
    secret: clientSecret
  }, 
  auth: {
    tokenHost: 'shh',
    tokenPath: '/oauth2/v2.0/token',
    authorizePath: '/oauth2/v2.0/authorize'
  }
}

var scopes = [
  'openid',
  'profile',
  'offline_access',
];

var redirectUri = 'http://localhost:3000/';

module.exports = {
  registerClient: async function() {
    const client = new AuthorizationCode(config);
  
    client.authorizeURL({
      redirect_uri: redirectUri,
      scope: scopes.join(' ')
    });
  
    const tokenParams = {
      code: '302',
      redirect_uri: redirectUri,
      scope: scopes.join(' '),
    };
  
    try {
      const accessToken = await client.getToken(tokenParams);
      return accessToken;
    } catch (error) {
      console.log('Access Token Error', error.message);
    }
  }
}

React Component calling function in authHelper.js --

import React from "react";
import authHelper from "../Auth/authHelper";

handleClick = () => {
    console.log(authHelper.registerClient())
};
```

**Comment by jonathansamines** [comment]
Hi @pravMo This is most likely caused because you are using webpack to compile this application. Webpack is creating a pollyfill for you, but it probably has outdated pollyfill for the node's URL. 

As a side note, this library is not meant to be used in a browser context, not because we don't want to, but rather because these authentication flows are meant to be used on clients where confidentiality can be preserved. Note that the browser does not provide such guarantee.
