### ISSUE TITLE
How to use a refresh token without an access token for refreshing?

### ISSUE THREAD

**Issue by aabuhijleh** [lelylan/simple-oauth2#368]
#### Context

* *node version*: 12.5.0
* *module version*: 4.2.0
* *environment* (e.g. node, browser, native): node
* *any other relevant information*: not using a DB

#### The issue

In my case, tokens are stored on the client side exclusively 

This is how the server handles the refresh request
* get access & refresh tokens from the client
* create an AccessToken
* refresh it
```js
app.post("/refresh", async (req, res) => {
  // create a plain valid token object
  const validToken = {
    access_token: req.body.accessToken,
    refresh_token: req.body.refreshToken,
    expires_in: 3599,
    token_type: "Bearer",
    scope: "all",
  };
  const accessToken = client.createToken(validToken);
  const refershedToken = await accessToken.refresh();
  res.send(refershedToken);
}):
```

Is there a way to do this while requiring the client to send **ONLY** the refresh token?

Thanks in advance!

**Comment by jonathansamines** [comment]
Hi @aabuhijleh, from this library standup it should just work. However, if your OAuth 2 server requires the access token, there is nothing we can do on our side. Please re-open if additional details if you are getting an error.
