### ISSUE TITLE
The content-type is not JSON compatible when using simple-oauth2

### ISSUE THREAD

**Issue by vinay047** [lelylan/simple-oauth2#371]
Hello guys,

I am getting the **Json compatible issue** when i tried to hit the getToken(). I know this might be duplicate **but i didn't find the solution that will work** **for me** even i added **{json : 'force'} that time i am getting the different error "Response Error: 404 Not Found".**

Here is the code snippet  which i am using :- 

    const config = {
         client: {
         id: '<client-id>',
        secret: '<client-secret>'
      },
      auth: {
           tokenHost: 'https://api.oauth.com'
       }
    };
 
const { ClientCredentials } = require('simple-oauth2');

Here i need grant Type as "Cliend Credential".

    app.get("/", async (request, response) => {
        const clientsso = new ClientCredentials(config);
         const tokenParams = {
        scope:  'scope',
       };
    
    try { 
      const accessToken = await clientsso.getToken(tokenParams);
      console.log("Access token ----------- "+accessToken)
      return response
        .status(200)
        .send({ message: accessToken });
    } catch (error) {
      console.log('Access Token error', error.message);
      return response
        .status(500)
        .send({ message: "Access Token error", error: error.message });
     }
    });

Not Sure is their any mistake i am doing during configuration, please point me in right direction. 

Any help would be appreciated!.

**Comment by jonathansamines** [comment]
@vinay047 A 404 is most likely a hint that the `tokenHost/tokenPath` are not properly configured. It is hard to tell what the actual values should be without a complete working example and information about the authentication provider you are using. Feel free to reopen with the missing details.
