### ISSUE TITLE
Authorization set to Basic by default, sometimes Bearer is required

### ISSUE THREAD

**Issue by DeanWronowski** [lelylan/simple-oauth2#384]
Inside the request-options file it configures the request-options. 

On line 46, it has the following

requestOptions.headers.Authorization = `Basic ${credentials}`;

However, in some instances a bearer token is required as follows:

requestOptions.headers.Authorization = `Bearer ${credentials}`;

Would it be possible to have a flag to switch from 'Basic' to 'Bearer'?

**Comment by jonathansamines** [comment]
Hi @DeanWronowski are you having problem with a particular service? Is it failing in a particular operation (e.g get access token or refresh)?

**Comment by DeanWronowski** [comment]
Hi @jonathansamines 
Thanks for replying. The service is Sage Accounting - https://developer.sage.com/api/accounting/guides/authentication/

It requires a bearer token in the header

It’s both requests - access token and refreshing

Hope that helps,

**Comment by jonathansamines** [comment]
I just checked that service and seems like you actually need to use form authentication. You can enable that by using `options.authorizationMethod` set to `body`. The information presented at the provided document, represent how you communicate with the service once you already have an access token.

**Comment by DeanWronowski** [comment]
That worked perfectly - much appreciated,
