### ISSUE TITLE
Auto-push to package registry

### ISSUE THREAD

**Issue by HerrMuellerluedenscheid** [lelylan/simple-oauth2#388]
Hi,
I see that the [hosted package](https://www.npmjs.com/package/simple-oauth2) was realeased a year ago. Given that there are about 80k weekly downloads from there I'm wondering if this shouldn't be updated more regularly. There is a github action which seems to automate that: https://github.com/marketplace/actions/publish-to-npm

Would that be a good solution to keep the repo and the package more in sync?

Best
Marius

**Comment by jonathansamines** [comment]
Hey @HerrMuellerluedenscheid Thanks for looking at this, but presently this package does not have a high release cadence, so I am not really looking into automating the publishing process.
