### ISSUE TITLE
Authentication failed for microsoft account.

### ISSUE THREAD

**Issue by azamsolix** [lelylan/simple-oauth2#391]
#### Context

* *node version*:v14.17.5
* *module version*:83
* *environment* (e.g. node, browser, native):node
* *any other relevant information*:

#### How can we help?

Hi sir,
I am getting access token and refresh token both and by using access token i am trying to connect to IMAP but it is returning authentication error.I don't know what  i am doing wrong.Below is the complete source code
```js
const app = require('express')();
var cors = require('cors');
var bodyParser = require('body-parser');
app.use(cors());
app.use(bodyParser.json());

const { ClientCredentials, ResourceOwnerPassword, AuthorizationCode } = require('simple-oauth2');
const { Base64Encode } = require('base64-stream');
app.get('/callback', async function (req, res) {
     let credentials = {
  client: {
     id: "id",
      secret: "secret",   
  },
    auth: {
        tokenHost: 'https://login.live.com',
        tokenPath: '/oauth20_token.srf',
        authorizePath: '/oauth20_authorize.srf',
      }
    };
    const client = new AuthorizationCode(credentials);
    console.log('code', req.query);
     const tokenParams = {
    code: req.query.code,
    redirect_uri: 'http://localhost:3000/callback',
    scope:[
    'openid',
    'offline_access',
        'https://graph.microsoft.com/mail.read',
    "https://graph.microsoft.com/IMAP.AccessAsUser.All"
  ],
  };

  try {
      const accessToken = await client.getToken(tokenParams);
      console.log('accesstoken', accessToken, accessToken.token.access_token);
            let token=Buffer.from("user=email2021@hotmail.com" + "\x01auth=Bearer " + accessToken.token.access_token + "\x01\x01").toString('base64');
      console.log('ans', token)
      let Imap = require('imap');

             var imap = new Imap({
            xoauth2 :token,
        host: 'outlook.office365.com',
        port: 993,
        tls: true,
        authTimeout: 3000,
    tlsOptions: { rejectUnauthorized: false }
});
imap.connect();
imap.once('ready', function() {
      
    //   }
    });     
   imap.once('end', function() {
            console.log('Connection ended');
            // res.redirect('/name');
});          
  } catch (error) {
    console.log('Access Token Error', error);
  }
});
app.get('/auth', async function (req, res) {
    

    let credentials = {
  client: {
     id: "id",
      secret: "secret",   
  },
    auth: {
        tokenHost: 'https://login.live.com',
        tokenPath: '/oauth20_token.srf',
        authorizePath: '/oauth20_authorize.srf',
      },
      options: {
      authorizationMethod: 'body',
    }
    };
    const client = new AuthorizationCode(credentials);

   const authorizationUri = client.authorizeURL({
    redirect_uri: 'http://localhost:3000/callback',
    scope:  [
    'openid',
    'offline_access',
        'https://graph.microsoft.com/mail.read',
        'profile',
    "https://graph.microsoft.com/IMAP.AccessAsUser.All"
  ],
    state: 'azam'
  });
    console.log('aaaa,', authorizationUri);
    res.redirect(authorizationUri)
})

app.listen(3000, function() {
  console.log(`Express server started on  http://localhost:3000`);
});

```
Thanks 
Azam

**Comment by jonathansamines** [comment]
Hey @azamsolix What error are you getting back? Have you looked at [this](https://github.com/lelylan/simple-oauth2/blob/master/example/microsoft.js)? You may find something useful there to complete your integration.

**Comment by azamsolix** [comment]
Sir below is the error i am getting.

* OK The Microsoft Exchange IMAP4 service is ready. [QgBNAFgAUABSADAAMQBDAEEAMAAwADAANAAuAEkATgBEAFAAUgBEADAAMQAuAFAAUgBPAEQALgBPAFUAVABMAE8ATwBLAC4AQwBPAE0A]'
=> 'A0 CAPABILITY'
<= '* CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN AUTH=XOAUTH2 SASL-IR UIDPLUS ID UNSELECT CHILDREN IDLE NAMESPACE LITERAL+'
<= 'A0 OK CAPABILITY completed.'
=> 'A1 AUTHENTICATE XOAUTH2 dXNlcj1zYXRoeWFrcmlzaG5hMjAyMUBob3RtYWlsLmNvbQFhdXRoPUJlYXJlciBFd0JvQThsNkJBQVV3aWhyckNybVE0d3VJSlg1bWJqN3JRbGE2VFVBQWVwbStzbGNUV3JJdFE3MWtRVWo3L0xtNEhPMmdmd25oMWxBME1ySjZ1M0ZRWC9YTmlFSEhNZzNkUW8xc0ZQdk42MUNCMHFka2pvQzJuMVgwUkRsYklyWXZnZ1Y4LzI5SzhtbGpUZ3VnUUdrRG95cUtFV3JDdGRHMU5XWFJzY29SYW5FZ2t4S0gyOGFrSTRDNFhxRHA5a1lVZ1h3WFhMK3gva0o5OENiZ0hNcGZrVnJDK1VrSlBUSzQrR1AremNsTXBpQzdRbmFzTkh2WHNwUTdSVEwzdTBMakhaYmRwWVVXYjNrbzhnZ0NQaU1weGJyTCtQYjM0azlRN1JYUTkxME1XSzVyV1hHMmM5d3BFV3ZxSWFGYldGMlJIVjhWcE9YNVZKZUN0WFVRNlROczhGUnVVMWxKekFYWk95dUNzWVh3Uml3ZEpSV1FwdzU0Zm5pTkZiMm4zVURaZ0FBQ0pwVUtoSWZ2eEJsT0FLT3A0dGtyendrRmZYR0ZJYjlkd2IxUGZnaUt3djRibFNXdUhGWjRhU1FnNjZYWk9VbENoMUJHdU1mb2dJY0lxV3ZmR25EaUhkb2lsWm9Ccm9UWnZnZnlwREw0OW8yN0ZleloyMVhFNHE4SUNsMTdNSmlWNk1zK2laRGVMa3BDU1VORER6dlAxMkRNaHRCMTNaUEp1Qm9TOHlwYUJlU2R6YmJsWm5XZFFPUkNFY010enArUmdlSyt1YlNpUmJhdU5yT244V0tKeUJnZUMwM0xYdDNNUHJXTkZ6SU5rVXdFRU1weTBQYUNGUkx5QitCdmFTbzd1RkJEQUFzNjkxRVJKRjJzWUlIMTZ4eWF0elRBWEpPQklmSW43R3JLbzR6NEFSZ3ZPSG1HdTNRZUc5NWlmSUZjNnVMMlJETi9uek1WWnJvM3luWXRxOXRIU3Q2UmdIUTV1ZnZXZW1GN0V0WE9weGQ2dkJybTZmQldpdWxOaE13NGV3Ni83T2VPRGZuR1krdEc2YldXQUZGZWJpeGl5S2FrUWdsa25oaVBWa1JteTBybm5Ca1VVOU8xNndxZy9NdTkyN3FUVU13Q042T0VyRSt0UWg2bEZHb1c1WVFSRUdkbjA5SUlqdnB0ZkhFcHltQkdkTE5IVGpPc0lCa0VoeDBxTDZlOG9LUURUYTc0NnRSaXNOUmVuenpDUlI3enJobVhwM0pXYitDTW5EQlJiT2RXdzNEdXhnd0NuSXNoTU5RRTJQNFhuVE54QTF5clc2aHpqaVFTK29hT0YwSjZTWGN4bk8wclZzOURrajlTNk9hOTdBcEZ2RGNHekE4enhXa3B5YVFIdFpsU1hSL28wWTZzaml3MUcybndiWnA1TDZJT0kwLzFYMU1kQUgvUm5oSVZQTENsYUtmc2YzYlB2UEw1UUpMU1p4MmhRWmc0UUZlUU5wK2prdmNUODdlY2Q0L3NDTmcxeHI3d3hPL3JsMlk0LzZoY0Z5MjJiWFJJeHczbWo0Z2hBST0BAQ=='
<= 'A1 NO AUTHENTICATE failed.'
events.js:377
throw er; // Unhandled 'error' event
^

Error: AUTHENTICATE failed.

I am getting both access token and refresh token and then i am encoding access token to base64 and passing it to imap npm and it is returning authentication failed.


Thanks for helping me 
Azam ahmed
