### ISSUE TITLE
Microsoft ADAL to MSAL migration using simple-Oauth2

### ISSUE THREAD

**Issue by manisrivastav** [lelylan/simple-oauth2#392]
Does simple-oauth2 uses MSAL to authenticate and generate token with azure AD?
I was asked by Microsoft azure support to check with simple-oauth2 team about which auth module is being used in the background for token generation with Microsoft azure. 

after June 30 2022, ADAL will no-longer available, so every one should move to MSAL. 

currently using "simple-oauth2": "^4.3.0", with node version 12.21.0

**Comment by jonathansamines** [comment]
See:

> [Simple OAuth2](https://github.com/lelylan/simple-oauth2#simple-oauth2) is a Node.js client library for the [OAuth 2.0](http://oauth.net/2/) authorization framework. [OAuth 2.0](http://oauth.net/2/) is the industry-standard protocol for authorization, enabling third-party applications to obtain limited access to an HTTP service, either on behalf of a resource owner or by allowing the third-party application to obtain access on its own behalf.

I don't know the answer for anything more specific than that. You'll have to check how are you using this library to integrate with their services.
