### ISSUE TITLE
How to access .request() function?

### ISSUE THREAD

**Issue by yaneony** [lelylan/simple-oauth2#393]
There is a nice .request() function https://github.com/lelylan/simple-oauth2/blob/master/lib/client/client.js#L33 which can be used for additional queries, for example, to fetch user profile with an access token. But how to access that function?!

Thanks!

**Comment by jonathansamines** [comment]
Hello @yaneony. It is not really possible to expose that function as it is designed to be an internal implementation detail. The existing API use to perform requests to their specifics host (e.g tokenHost or authorizationHost) and will always include the authorization headers, making it not suitable for general usage. I recommend you checkout the underlying library we use: [wreck](https://github.com/hapijs/wreck).
