### ISSUE TITLE
accessToken.refresh throwing 401 not authorize error.

### ISSUE THREAD

**Issue by shashi-syngenta** [lelylan/simple-oauth2#398]
```
const client = new AuthorizationCode(auth_config);
  let accessToken = await client.createToken(JSON.parse(accessTokenjson));
  try {
    const refreshParams = {      
      scope: "",
    };
    let accessTokenval = await accessToken.refresh(refreshParams, { json: true, rejectUnauthorized: false });
    return accessTokenval;
  } catch (error) {
    console.log("Error refreshing access token: ", error.message);
  }
```

#### Context

* *node version*: 14.17.0
* *module version with issue*: 4.3.0
* *last module version without issue*: issue is in all version
* *environment* (e.g. node, browser, native): Node
* *any other relevant information*:

#### What are you trying to achieve or the steps to reproduce?

Calling .refresh to get refresh token, but API is throwing 401 unauthorize issue

```js
const some = 'properly formatted code example';
```

#### What result did you expect?

![image (3)](https://user-images.githubusercontent.com/85622097/169259681-ad020b0b-0d27-4362-ac6c-56291cd351e8.png)
![image (4)](https://user-images.githubusercontent.com/85622097/169259691-4477b9af-349f-4dde-a1c3-30adfd39e4a5.png)

**Comment by jonathansamines** [comment]
Hey @shashi-syngenta The `www-authenticate` response header will usually contain additional information as to why the authentication failed. Other than that, please create a new issue with a self-contained reproduction to take a look at.
