### ISSUE TITLE
Does not work with pushbullet.

### ISSUE THREAD

**Issue by Efreak** [lelylan/simple-oauth2#40]
I'm not entirely certain if this is the only problem, but at the very least tokens requests and authorization requests don't use the same hostname, and this isn't supported by this module.

You need to authorize at http://**pushbullet.com**/authorize, however token requests go to http://**api.pushbullet.com**/oauth/token. More info on pushbullet's oauth api is available in their [docs](https://docs.pushbullet.com/#oauth).

**Comment by andreareginato** [comment]
Thanks for writing @Efreak. I guess we need a PR to make this work. Anyway, it's a bit of a strange behaviour.

**Comment by jonathansamines** [comment]
This is a little weird behaviour, but it was already already requested previously in #29 and also i can remember that some google apis work in this way. We need to think in a way to add support to this in future versions.

**Comment by jonathansamines** [comment]
May we can have to separate configurable endpoints (ie. by adding **authorizeSite** property) and taking it in account only for the "authorize" grant to make the internal call to the api to a different endpoint (keeping the authorizationPath) and resolve that path to the new **authorizeSite** property if present, and if not present, resolve it based on the current **site** property.

@Efreak what was your solution to this problem?
@andreareginato should we implement this behaviour?

**Comment by Efreak** [comment]
I haven't actually done anything at all yet. I plan to rewrite the notification plugin of [steam-chat-bot](https://github.com/efreak/node-steam-chat-bot) to authenticate in the browser instead of pasting api keys into private messages, but I haven't even started this yet, as I've been busy (so far as I'm working on it at all) doing other things. If I ever get back to that plugin and figure out a solution, I'll let you know.

**Comment by andreareginato** [comment]
@jonathansamines this looks kind of strange, but I see, it happens. 
How much would be the expected effort to make the needed changes?

**Comment by jonathansamines** [comment]
Closed by #75
