### ISSUE TITLE
Access token additional claims

### ISSUE THREAD

**Issue by 7uker** [lelylan/simple-oauth2#400]
#### Context

* *node version*: 14.15.1
* *module version*: 4.3.0
* *environment* (e.g. node, browser, native): node
* *any other relevant information*:

#### How can we help?

Are all claims in access token visible, or only the ones specified in https://www.rfc-editor.org/rfc/rfc7519 ?
I am implementing SP for a customer IdP and they claim that their custom claims are passed to my API, but I see only standard claims.

Thank you very much, I am going in circles.

```js
const accessToken = await client.getToken(options);
console.log('The resulting token: ', accessToken);
```

**Comment by jonathansamines** [comment]
Hello @7uker Not really sure what you are referring to. This library does not offer explicit support for JWT tokens. Will close this issue, but please feel free to create a new one with a reproducible example of what exactly are you trying to achieve using this library.
