### ISSUE TITLE
400 status code when try to login via LinkedIn 

### ISSUE THREAD

**Issue by alexanderkhivrych** [lelylan/simple-oauth2#401]
#### Context

* *node version*: 16
* *module version with issue*: latest 4.3.0
* *last module version without issue*: it looks like LinkedIn changed API
* *environment* (e.g. node, browser, native): node
* *any other relevant information*:

#### What are you trying to achieve or the steps to reproduce?

This code has been in production for six months, then it stopped working. 
```js
       const { token } = await client.getToken({
          code: request.query.code,
          redirect_uri: linkedinRedirectUrl.toString(),
          scope: 'r_liteprofile, r_emailaddress',
        });
```

The client secret and all needed config are specified initially when I create a new instance of the  `AuthorizationCode` client.

```
  const client = new AuthorizationCode({
    client: {
      id: process.env.LINKEDIN_CLIENT_ID,
      secret: process.env.LINKEDIN_CLIENT_SECRET,
    },
    auth: {
      authorizeHost: 'https://www.linkedin.com',
      authorizePath: '/oauth/v2/authorization',
      tokenHost: 'https://www.linkedin.com',
      tokenPath: '/oauth/v2/accessToken',
    },
  });
```

It does not use the specified `secret` from the initial config.

Moreover, It looks like LinkedIn changed API and responded with 400 bad requests, and to fix the issue, you need to add the client secret regarding LinkedIn documentation   https://learn.microsoft.com/en-us/linkedin/shared/authentication/authorization-code-flow?context=linkedin%2Fcontext&view=li-lms-2022-08&tabs=HTTPS#step-3-exchange-authorization-code-for-an-access-token

`client_secret: process.env.LINKEDIN_CLIENT_SECRET,`.

To fix I need to add client_secret : 

```js
       const { token } = await client.getToken({
          code: request.query.code,
          redirect_uri: linkedinRedirectUrl.toString(),
          scope: 'r_liteprofile, r_emailaddress',
          client_secret: process.env.LINKEDIN_CLIENT_SECRET,
        });
```

 Although it works now, it looks like this property was not expected in this library, which is why I got a typescript error:

```
Argument of type '{ code: string; redirect_uri: string; scope: string; client_secret: string; }' is not assignable to parameter of type 'AuthorizationTokenConfig'.
  Object literal may only specify known properties, and 'client_secret' does not exist in type 'AuthorizationTokenConfig'.ts(2345)
```

**Comment by alexanderkhivrych** [comment]
added example https://github.com/lelylan/simple-oauth2/pull/402

**Comment by jonathansamines** [comment]
Hello @alexanderkhivrych I just had a quick look at your problem. I think what you are looking for is to change the `authorizationMethod` to `body`, that will make sure your credentials are added to the payload as opposed to the header. See [options](https://github.com/lelylan/simple-oauth2/blob/master/API.md#options):


> - `authorizationMethod` - Method used to send the client.id/client.secret authorization params at the token request. Valid options are header or body. If set to body, the bodyFormat option will be used to format the credentials. Defaults to header

**Comment by alexanderkhivrych** [comment]
@jonathansamines Thank you. It is working. I am sure LinkedIn stopped using headers for security reasons, and the integration stopped working. I hope this issue might be helpful for the community with Linkedin Integration. 

Moreover, I added PR with LinkedIn example @jonathansamines. Could you please review https://github.com/lelylan/simple-oauth2/pull/402? It will be useful for the community and may speed up integration with Linkedin :)
