### ISSUE TITLE
Omit scope parameter in requests

### ISSUE THREAD

**Issue by simplypress** [lelylan/simple-oauth2#413]
#### Context

* *node version*: v18.12.1
* *module version*: 5.0.0
* *environment* (e.g. node, browser, native): node
* *any other relevant information*: Using TypeScript

#### What problem are you trying to solve?

I am using this library to implement the `ResourceOwnerPassword` flow in my server application. I am authenticating with [Salesforce](https://www.salesforce.com/au/), which does NOT support the `scope` parameter in any of its OAuth2 flows, and returns an error if it's included. There doesn't seem to be a way to omit this parameter from the request using this library. 

I couldn't find anyhting in the minmal docs, and am getting an error if I don't include this parameter in TypeScript.

#### Do you have a new or modified API suggestion to solve the problem?

Make the scope paramter optional.

**Comment by jonathansamines** [comment]
We don't maintain our own type definitions. Might want to contribute those changes to the DefinitelyTyped repository.
