### ISSUE TITLE
Not human readable errors and cannot revoke if JSON strict mode

### ISSUE THREAD

**Issue by ReshetovItsMe** [lelylan/simple-oauth2#416]
#### Context

* *node version*: 14.20.1
* *module version with issue*: 5.0.0
* *last module version without issue*: -
* *environment* (e.g. node, browser, native): node
* *any other relevant information*: hydra as oauth provider

#### What are you trying to achieve or the steps to reproduce?

I'm doing `ClientCredentials` grant type request. I'm trying to pass JSON parsing mode as `strict` in `http` option. After it I have following code:
```js
accessToken.revokeAll();
```

#### What was the result you got?
Got following error:
```json
{
  "statusCode": 406,
  "payload": {
    "statusCode": 406,
    "error": "Not Acceptable",
    "message": "The content-type is not JSON compatible"
  },
  "headers":{}
}
```

#### What result did you expect?

Tokens should be revoked. Errors should be human readable.

#### BONUS:

Even if pass JSON parsing mode as `false`. We always got `circular structure to JSON` error on any reason (for example wrong `tokenPath`):

**Comment by jonathansamines** [comment]
Feel free to reopen with a complete reproduction example. Otherwise, can't really help.
