### ISSUE TITLE
Extend refresh_token function to include optional parameters

### ISSUE THREAD

**Issue by patricksteenks** [lelylan/simple-oauth2#85]
I'm using simple-oauth2 to connect to the Oauth REST API of Exact. When using the refresh function, I do however have to change this function, because there are some extra parameters needed to send to Exact when asking for a refreshtoken.

These extra parameters are clientId and clientSecret, next to the current parameters grant_type and refresh_token.

Would it be possible to extend this function, so that you can send your own optional parameters? Something like:

`token.refresh(params, function(error, result) {`

in stead of just
`token.refresh(function(error, result) {`

**Comment by jonathansamines** [comment]
Hi @patricksteenks I am really sorry about the late response, but I think that feature is already on simple-oauth@0.8.0. Please feel free to open if the issue persist.
