### ISSUE TITLE
Modifying global date prototype

### ISSUE THREAD

**Issue by gingermusketeer** [lelylan/simple-oauth2#86]
Ran into an issue recently where we were trying to understand where the `.compare` method available on date objects was coming from. Took a bit of time to realise that it was added by the `date-utils` library used by this module.

Is this something you would be open to changing?

Reasoning I can think of for changing this are:
- Making environment more predictable (only standard js/node features available)
- Avoiding global version differences (what happens if two modules include different versions of `date-utils`)
- Making it easier to know where apis are defined (need to require it explicitly)

Hope this make sense!

**Comment by jonathansamines** [comment]
I am completely aware of this problem. I´ll try to look for alternatives for achieving the date comparison. If you have any suggestion, I would be glad to accept a PR for this :)

**Comment by gingermusketeer** [comment]
@jonathansamines I have had a go at making this change in #90. Let me know if you want anything changed. I replaced date-utils with https://date-fns.org/ It is very well documented and I found it very straight forward to replace date-utils

**Comment by gingermusketeer** [comment]
This was fixed in #90 closing
